"""First normalized patient spine; frozen schema, no application model imports."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001'
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'unit', name='uq_concept_unit')
    )
    op.create_index(op.f('ix_concepts_code'), 'concepts', ['code'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projection_checkpoints',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('clinic_members',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'clinic_id')
    )
    op.create_table('owners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_clinic_id'), 'owners', ['clinic_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index('patients_order', 'patients', ['clinic_id', 'name', 'id'], unique=False)
    op.create_table('owner_patients',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'patient_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_clinic_id'), 'sources', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_sources_patient_id'), 'sources', ['patient_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('actor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'dedupe_key', name='uq_event_dedupe')
    )
    op.create_index('events_timeline', 'events', ['clinic_id', 'patient_id', 'occurred_at', 'id'], unique=False)
    op.create_index(op.f('ix_events_clinic_id'), 'events', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_events_patient_id'), 'events', ['patient_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ref_low', sa.Float(), nullable=True),
    sa.Column('ref_high', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_concept_id'), 'observations', ['concept_id'], unique=False)
    op.create_index(op.f('ix_observations_event_id'), 'observations', ['event_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_event_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_concept_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_events_patient_id'), table_name='events')
    op.drop_index(op.f('ix_events_clinic_id'), table_name='events')
    op.drop_index('events_timeline', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sources_patient_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_clinic_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('owner_patients')
    op.drop_index('patients_order', table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_owners_clinic_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('clinic_members')
    op.drop_table('projection_checkpoints')
    op.drop_table('people')
    op.drop_index(op.f('ix_concepts_code'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('clinics')
    # ### end Alembic commands ###
