'use client';
import {useState,useEffect,useRef} from 'react';
import {useWorkspace} from '@/lib/workspace';
import {api} from '@/lib/api';
import {TwilioTrial} from './TwilioTrial';
import {Badge,BusyButton,Form,SourceModal,patientOptions} from './ui';
import {Row} from '@/lib/types';

export function SavedViews(){
 const w=useWorkspace(),views=w.records.filter(r=>r.kind==='dashboard'&&!r.data.archived);
 const [selected,setSelected]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState('');
 const [source,setSource]=useState<Row|null>(null),[loading,setLoading]=useState(false);const request=useRef(0);
 const refresh=async(id=selected)=>{
  const current=++request.current;setError('');setData(null);setSource(null);setLoading(Boolean(id));
  if(!id)return;
  try{const result=await api('/dashboards/'+id);if(current===request.current)setData(result)}
  catch(e){if(current===request.current)setError((e as Error).message)}
  finally{if(current===request.current)setLoading(false)}
 };
 useEffect(()=>{setSelected('');setData(null);setSource(null);setLoading(false);return()=>{request.current++}},[w.snapshot?.clinic.id]);
 return <section className="panel section-gap"><div className="panel-heading"><h2>Saved record views</h2><Badge>Live queries</Badge></div><div className="modal-body"><select aria-label="Saved record view" value={selected} onChange={e=>{setSelected(e.target.value);void refresh(e.target.value)}}><option value="">Choose a saved view</option>{views.map(r=><option key={r.id} value={r.id}>{r.data.name}</option>)}</select>{selected&&<BusyButton disabled={loading} onClick={()=>refresh()}>Refresh results</BusyButton>}{loading&&<p role="status">Loading saved view…</p>}{error&&<p role="alert" className="error">{error}</p>}{data&&<><h3>{data.data.name}</h3><p>{data.result.count} matching records · refreshed {new Date(data.result.refreshed_at).toLocaleTimeString()}</p><p>{data.result.filter_summary} · {data.result.timezone}</p>{data.result.groups.map((g:any)=><p key={g.label}>{g.label}: {g.count}</p>)}<details><summary>Matching records ({data.result.records.length} of {data.result.count})</summary><div className="receipts">{data.result.records.map((r:Row)=><button key={r.id} onClick={()=>setSource(r)}>{r.data.title||r.data.name||r.data.number||r.kind}</button>)}</div>{data.result.truncated&&<p>Showing the first {data.result.record_limit} records. Narrow the filters to see a smaller set.</p>}</details><BusyButton onClick={async()=>{await w.act('dashboard.delete',{id:data.id,version:data.version});setData(null);setSelected('')}}>Delete view</BusyButton></>}</div><Form submit="Save record view" fields={[{name:'name',label:'View name',required:true},{name:'kind',label:'Records',options:['event','observation','invoice','appointment','inventory','reminder'].map(x=>({value:x,label:x}))},{name:'patient_id',label:'Patient (optional)',options:[{value:'',label:'Whole clinic'},...patientOptions(w.records)]},{name:'start',label:'From',type:'date'},{name:'end',label:'Through',type:'date'}]} onSubmit={async p=>{const r=await w.act('dashboard.save',{name:p.name,query:{kind:p.kind,patient_id:p.patient_id||null,start:p.start||null,end:p.end||null}});setSelected(r.id);await refresh(r.id)}}/>{source&&<SourceModal source={source} onClose={()=>setSource(null)}/>}</section>
}

export function TestConnections(){
 const w=useWorkspace();const [status,setStatus]=useState<any>(null),[error,setError]=useState('');
 const admin=w.snapshot?.actor.data.role==='admin';
 useEffect(()=>{if(admin)void api('/operations/status').then(setStatus).catch(e=>setError(e.message))},[admin,w.snapshot?.clinic.id]);
 if(!admin)return null;
 const messages=w.records.filter(r=>r.kind==='test_message'),payments=w.records.filter(r=>r.kind==='test_payment');
 return <section className="section-gap"><TwilioTrial/><h2>Integration rehearsal</h2><p>Simulation only. These controls send no messages, move no money and leave invoice balances unchanged. Existing WhatsApp is untouched.</p>{error&&<p className="error">{error}</p>}{status&&<p>Sending disabled · {status.pending_escalations} urgent submissions need attention</p>}
 <details><summary>Test message delivery states</summary><Form submit="Create simulated message" fields={[{name:'patient_id',label:'Patient',required:true,options:patientOptions(w.records)},{name:'body',label:'Test message',required:true,type:'textarea'}]} onSubmit={async p=>{await w.act('test.message.create',p)}}/>{messages.map(r=><div className="file-row" key={r.id}><span>{r.data.body}</span><Badge>{r.data.status}</Badge>{({queued:['accepted','failed'],accepted:['delivered','failed'],delivered:['read'],failed:['queued'],read:[]} as Record<string,string[]>)[r.data.status].map(s=><BusyButton key={s} onClick={async()=>{await w.act('test.message.callback',{id:r.id,status:s})}}>Simulate {s}</BusyButton>)}</div>)}</details>
 <details><summary>Test payment callbacks</summary><Form submit="Create simulated payment" fields={[{name:'invoice_id',label:'Invoice',required:true,options:w.records.filter(r=>r.kind==='invoice'&&!['paid','void'].includes(r.data.status)).map(r=>({value:r.id,label:r.data.number}))},{name:'amount_cents',label:'Amount in cents',type:'number',min:1,required:true}]} onSubmit={async p=>{await w.act('test.payment.create',p)}}/>{payments.map(r=><div className="file-row" key={r.id}><span>SGD {(r.data.amount_cents/100).toFixed(2)} · refunded {(r.data.refunded_cents/100).toFixed(2)}</span><Badge>{r.data.status}</Badge>{r.data.status==='pending'&&['succeeded','failed'].map(s=><BusyButton key={s} onClick={async()=>{await w.act('test.payment.callback',{id:r.id,status:s})}}>Simulate {s}</BusyButton>)}{r.data.status==='succeeded'&&r.data.refunded_cents===0&&<BusyButton onClick={async()=>{await w.act('test.payment.refund',{id:r.id,amount_cents:r.data.amount_cents,reason:'Synthetic refund rehearsal'})}}>Simulate full refund</BusyButton>}</div>)}</details>
 <details><summary>Receive a synthetic laboratory result</summary><Form submit="Receive synthetic result" fields={[{name:'patient_id',label:'Patient',required:true,options:patientOptions(w.records)},{name:'accession',label:'Unique test report reference',required:true},{name:'value',label:'Potassium (mmol/L)',type:'number',step:'any',required:true},{name:'ref_low',label:'Range minimum from report',type:'number',step:'any',required:true},{name:'ref_high',label:'Range maximum from report',type:'number',step:'any',required:true}]} onSubmit={async p=>{await w.act('test.lab.receive',{patient_id:p.patient_id,dedupe_key:'synthetic:'+p.accession,occurred_at:new Date().toISOString(),summary:'Synthetic potassium report '+p.accession,source:{kind:'document',id:p.accession,page:1,text:`Synthetic potassium ${p.value} mmol/L; supplied range ${p.ref_low}–${p.ref_high}.`},observations:[{concept:'potassium',name:'Potassium',value:Number(p.value),unit:'mmol/L',ref_low:Number(p.ref_low),ref_high:Number(p.ref_high)}]});w.notify('Synthetic lab result saved to the patient timeline')}}/></details>
 <h3>Urgent owner submissions</h3><p>This queue requires staff attention. No external emergency alert is sent.</p>{w.records.filter(r=>r.kind==='escalation').map(r=><div className="file-row" key={r.id}><span>{w.records.find(p=>p.id===r.data.patient_id)?.data.name}</span><Badge>{r.data.status}</Badge>{r.data.status==='needs_attention'&&<BusyButton onClick={async()=>{await w.act('escalation.acknowledge',{id:r.id,version:r.version})}}>Acknowledge</BusyButton>}</div>)}
 </section>
}

export function SchedulePreferences(){
 const w=useWorkspace();const config=w.records.find(r=>r.kind==='schedule');
 if(w.snapshot?.actor.data.role!=='admin')return null;
 return <details className="section-gap"><summary>Rooms and staff availability</summary><p>Choose a weekday and time window for a staff member. Saving replaces that member’s schedule; other staff retain their settings.</p><Form submit="Save availability" fields={[{name:'rooms',label:'Room names, separated by commas',value:config?.data.rooms?.join(', ')||''},{name:'member',label:'Staff member',required:true,options:w.records.filter(r=>r.kind==='member'&&r.data.active).map(r=>({value:r.id,label:r.data.name}))},{name:'weekday',label:'Weekday',options:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((label,i)=>({value:String(i),label}))},{name:'start',label:'Available from',type:'time',required:true},{name:'end',label:'Available until',type:'time',required:true}]} onSubmit={async p=>{await w.act('schedule.configure',{version:config?.version,rooms:p.rooms.split(',').map((x:string)=>x.trim()).filter(Boolean),availability:{...config?.data.availability,[p.member]:{[p.weekday]:[{start:p.start,end:p.end}]}}});w.notify('Scheduling rules saved')}}/></details>
}

export function AccountControls(){
 const w=useWorkspace();const [invitation,setInvitation]=useState<any>(null),[mfa,setMfa]=useState<any>(null),[enabled,setEnabled]=useState(false),[recovery,setRecovery]=useState<string[]>([]);
 return <section className="section-gap"><h3>Staff sign-in</h3>{w.snapshot?.actor.data.role==='admin'&&<><Form submit="Create invitation" fields={[{name:'member_id',label:'Member to invite',required:true,options:w.records.filter(r=>r.kind==='member'&&r.data.active).map(r=>({value:r.id,label:r.data.name}))}]} onSubmit={async p=>setInvitation(await api('/account/invitations',{method:'POST',body:JSON.stringify(p)}))}/>{invitation&&<div className="modal-body"><p>Share privately with the named staff member. Expires {new Date(invitation.expires_at).toLocaleString()}. No email has been sent.</p><input aria-label="Staff invitation link" readOnly value={location.origin+'/enroll#token='+invitation.token}/><button className="secondary" onClick={()=>setInvitation(null)}>Hide invitation</button></div>}</>}
 {w.snapshot?.mode==='password'&&<><details><summary>Enable an authenticator</summary><p>Add the setup key to an authenticator app, then verify its six-digit code. Save the recovery codes after setup; each can be used once if you lose your authenticator.</p>{!mfa&&!enabled&&<Form submit="Create authenticator key" fields={[{name:'password',label:'Current password',type:'password',required:true}]} onSubmit={async p=>setMfa(await api('/account/mfa/setup',{method:'POST',body:JSON.stringify(p)}))}/>} {mfa&&!enabled&&<><p>Account: {mfa.account}</p><label>Setup key<input readOnly value={mfa.secret}/></label><Form submit="Enable authenticator" fields={[{name:'code',label:'Authenticator code',required:true}]} onSubmit={async p=>{const result=await api('/account/mfa/confirm',{method:'POST',body:JSON.stringify(p)});setRecovery(result.recovery_codes);setMfa(null);setEnabled(true)}}/></>}{enabled&&<div><p>Authenticator enabled. Save these recovery codes privately; each works once.</p><pre>{recovery.join('\n')}</pre><button className="secondary" onClick={()=>setRecovery([])}>I saved the recovery codes</button></div>}</details><details><summary>Change your password</summary><Form submit="Change password and sign out" fields={[{name:'password',label:'Current password',type:'password',required:true},{name:'new_password',label:'New password (12+ characters)',type:'password',required:true},{name:'code',label:'Authenticator code (if enabled)'}]} onSubmit={async p=>{await api('/account/password',{method:'POST',body:JSON.stringify(p)});location.reload()}}/></details></>}
 </section>
}

export function OrganizationControls(){
 const w=useWorkspace();const [org,setOrg]=useState<any>(null),[ready,setReady]=useState(false);
 const refresh=async()=>{setOrg(await api('/organization'));setReady(true)};
 useEffect(()=>{setReady(false);void refresh().catch(e=>w.notify(e.message))},[w.snapshot?.clinic.id]);
 if(!ready||w.snapshot?.actor.data.role!=='admin')return null;
 return <details className="section-gap"><summary>Organization and master policies</summary>{org?<><h3>{org.name}</h3><p>{org.master?'Organization master':'Clinic administrator'} · {org.locked_actions.length} inherited restrictions</p>{org.master&&<><p>{org.clinics.map((c:any)=>c.name).join(' · ')}</p><Form submit="Create clinic" fields={[{name:'name',label:'New clinic name',required:true},{name:'timezone',label:'Timezone',value:'Asia/Singapore',required:true}]} onSubmit={async p=>{await w.act('organization.clinic_create',p);await refresh()}}/><form className="form" onSubmit={async e=>{e.preventDefault();try{await w.act('organization.policy',{actions:new FormData(e.currentTarget).getAll('lock')});await refresh()}catch{}}}><p>Inherited restrictions apply to clinic administrators as well as staff. The organization master retains access.</p>{['source.add','summary.generate','medication.dispense','payment.record','clinical.approve','share.create','message.queue'].map(a=><label key={a}><input type="checkbox" name="lock" value={a} defaultChecked={org.locked_actions.includes(a)}/>{a}</label>)}<button className="secondary">Save master policies</button></form></>}</>:<Form submit="Create organization for this clinic" fields={[{name:'name',label:'Organization name',required:true}]} onSubmit={async p=>{await w.act('organization.create',p);await refresh()}}/>}</details>
}

export function OntologyProposals(){
 const w=useWorkspace();const proposals=w.records.filter(r=>r.kind==='ontology_proposal');
 return <details className="section-gap"><summary>Dictionary proposals and synonyms</summary><p>Proposals cannot alter recorded facts or supply medical reference ranges. Accepted codes are immutable; use a new versioned code if meaning or units change.</p><Form submit="Propose dictionary entry" fields={[{name:'description',label:'Meaning and requested unit',required:true,type:'textarea'},{name:'code',label:'Stable code (manual proposal)'},{name:'name',label:'Display name (manual proposal)'},{name:'value_type',label:'Value type',options:['number','text','boolean'].map(value=>({value,label:value}))},{name:'unit',label:'Unit'},{name:'category',label:'Category'},{name:'aliases',label:'Synonyms (comma-separated codes)'},{name:'use_ai',label:'Proposal method',options:[{value:'false',label:'Use my definition'},...(w.snapshot?.integrations.ai?[{value:'true',label:'Ask AI to propose a definition'}]:[])]}]} onSubmit={async p=>{await w.act('ontology.propose',{description:p.description,use_ai:p.use_ai==='true',definition:{code:p.code,name:p.name,value_type:p.value_type,unit:p.unit,category:p.category,aliases:p.aliases.split(',').map((v:string)=>v.trim()).filter(Boolean)}})}}/>{proposals.map(r=><div className="modal-body" key={r.id}><h3>{r.data.definition.name}</h3><p>{r.data.definition.code} · {r.data.definition.value_type} · {r.data.definition.unit} · synonyms: {r.data.definition.aliases.join(', ')||'none'}</p><Badge>{r.data.status}</Badge>{r.data.status==='proposed'&&w.snapshot?.actor.data.role==='admin'&&['accepted','rejected'].map(status=><BusyButton key={status} onClick={async()=>{await w.act('ontology.review',{id:r.id,version:r.version,status})}}>{status==='accepted'?'Accept definition':'Reject'}</BusyButton>)}</div>)}</details>
}

export {IncomingTransfers} from './ClinicTransfers';

export function MigrationRehearsal(){
 const w=useWorkspace();const [plan,setPlan]=useState<any>(null),[payload,setPayload]=useState<any>(null);
 if(w.snapshot?.actor.data.role!=='admin')return null;
 return <details className="section-gap"><summary>Rehearse a mapped clinical migration</summary><p>Use a synthetic export containing a records array. Stable source IDs map to stable clinic IDs. Replays skip identical records; conflicting content stops the import. Financial history and binary media require a separate reconciliation process.</p><Form submit="Validate and preview mapping" fields={[{name:'source_system',label:'Source system identifier',required:true},{name:'json',label:'Clinical export JSON',type:'textarea',required:true,wide:true}]} onSubmit={async p=>{const parsed=JSON.parse(p.json);const candidate={source_system:p.source_system,records:parsed.records};const result=await w.act('migration.preview',candidate);setPayload(candidate);setPlan(result)}}/>{plan&&<div className="modal-body"><p>{plan.new_count} new records · {plan.unchanged_count} unchanged records</p><pre>{JSON.stringify(plan.counts,null,2)}</pre><BusyButton onClick={async()=>{const result=await w.act('migration.apply',{...payload,expected_digest:plan.digest});setPlan(null);w.notify(result.new_count+' records imported with stable source identities')}}>Apply reviewed mapping</BusyButton></div>}</details>
}

export function StockOrders(){
 const w=useWorkspace(),orders=w.records.filter(r=>r.kind==='purchase_order');
 if(w.snapshot?.actor.data.role!=='admin')return null;
 return <section className="panel section-gap"><div className="panel-heading"><h2>Purchase orders</h2></div><Form submit="Record purchase order" fields={[{name:'inventory_id',label:'Stock item',required:true,options:w.records.filter(r=>r.kind==='inventory'&&r.data.unit!=='service').map(r=>({value:r.id,label:r.data.name}))},{name:'supplier',label:'Supplier',required:true},{name:'quantity',label:'Units ordered',type:'number',min:1,required:true}]} onSubmit={async p=>{await w.act('purchase_order.create',p)}}/>{orders.map(r=><div className="file-row" key={r.id}><span>{w.records.find(i=>i.id===r.data.inventory_id)?.data.name} · {r.data.supplier} · {r.data.received}/{r.data.quantity} received</span><Badge>{r.data.status}</Badge>{!['received','cancelled'].includes(r.data.status)&&<BusyButton onClick={async()=>{await w.act('purchase_order.cancel',{id:r.id,version:r.version,reason:'Cancelled by administrator'})}}>Cancel remaining order</BusyButton>}</div>)}</section>
}
