'use client';
import React,{useEffect,useState,useSyncExternalStore} from 'react';
import {House,CalendarBlank,Users,Receipt,Package,FileText,EnvelopeSimple,GearSix,ChartBar,ArrowUpRight,MagnifyingGlass,Sparkle,WifiSlash,CheckCircle,Stethoscope,Microphone,ArrowLeft,Command,SidebarSimple,WarningCircle,X,ArrowRight} from '@phosphor-icons/react';
import {useWorkspace} from '@/lib/workspace';
import {recordingStore,recoverInterrupted,syncAudio} from '@/lib/recording';
import {Badge,PatientMark} from './ui';
import {Dashboard,Patients,PatientDetail} from './Patients';
import Consultation from './Consultation';
import Assistant from './Assistant';
import {PatientBrowser} from './PatientSpine';
import {Calendar,Clients,Handover} from './ClinicFlows';
import {Billing,Inventory,Messages,Templates,Reports,Settings} from './Operations';
const navigation=[['Home',House],['Patients',Users],['Clients',Users],['Handover',FileText],['Appointments',CalendarBlank],['Billing',Receipt],['Inventory',Package],['Templates',FileText],['Messages',EnvelopeSimple],['Reports',ChartBar],['Settings',GearSix]] as const;
export const navigate=(page:string,id?:string)=>{location.hash=encodeURIComponent(page)+(id?'/'+encodeURIComponent(id):'')};
export default function App(){const w=useWorkspace();const [route,setRoute]=useState(['Home','']),[assistant,setAssistant]=useState(false),[search,setSearch]=useState(''),[mobileNav,setMobileNav]=useState(false);const rec=useSyncExternalStore(recordingStore.subscribe,recordingStore.getSnapshot,recordingStore.getServerSnapshot);
 useEffect(()=>{const read=()=>{setRoute(location.hash.slice(1).split('/').map(decodeURIComponent));setSearch('');setMobileNav(false);window.scrollTo({top:0,behavior:'instant'})};read();window.addEventListener('hashchange',read);void recoverInterrupted().then(()=>syncAudio()).catch(()=>{});const on=()=>void recoverInterrupted().then(()=>syncAudio()).then(w.refresh).catch(()=>{});window.addEventListener('online',on);const t=setInterval(on,15000);return()=>{window.removeEventListener('hashchange',read);window.removeEventListener('online',on);clearInterval(t)}},[]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setAssistant(x=>!x)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(['requesting','recording','paused','saving'].includes(recordingStore.getSnapshot().status)){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[]);
 if(!w.snapshot)return <div className="loading-screen"><span className="wordmark">Broby<span>•</span></span><p>{w.error||'Opening your clinic workspace…'}</p>{w.error&&<button className="primary" onClick={()=>void w.refresh()}>Try again</button>}</div>;
 const [page,id]=route;const patientId=page==='Patient'?id:page==='Consultation'?w.records.find(r=>r.id===id)?.data.patient_id:undefined;
 const matches=w.records.filter(r=>r.kind==='patient'&&(r.data.name+' '+r.data.breed+' '+(w.records.find(o=>o.id===r.data.owner_id)?.data.name||'')).toLowerCase().includes(search.toLowerCase()));
 const active=page==='Consultation'||page==='Patient'?'Patients':page||'Home';
 return <div className="workspace"><a href="#main" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus()}}>Skip to content</a><aside className={'sidebar '+(mobileNav?'is-open':'')}><button className="wordmark" onClick={()=>navigate('Home')}>Broby<span>•</span></button><div className="sidebar-label">WORKSPACE</div><nav>{navigation.map(([label,Icon])=><button key={label} onClick={()=>navigate(label)} className={'nav-item '+(active===label?'active':'')}><Icon size={19} weight={active===label?'duotone':'regular'}/><span>{label}</span>{label==='Messages'&&w.records.filter(r=>r.kind==='outbox'&&r.data.status==='pending').length>0&&<small>{w.records.filter(r=>r.kind==='outbox'&&r.data.status==='pending').length}</small>}</button>)}</nav><div className="sidebar-bottom"><button className="assistant-launch" onClick={()=>setAssistant(true)}><Sparkle size={19}/><span>Ask Broby</span><kbd>⌘ K</kbd></button><div className="profile"><span className="avatar">AT</span><div><strong>{w.snapshot.actor.data.name}</strong><small>{w.snapshot.actor.data.role==='vet'?'Veterinarian':w.snapshot.actor.data.role}</small></div></div></div></aside>
 <div className="workspace-body"><header className="topbar"><div className="top-left"><button className="icon mobile-only" aria-label="Toggle navigation" onClick={()=>setMobileNav(!mobileNav)}><SidebarSimple size={22}/></button><Stethoscope size={18}/><select aria-label="Clinic" value={w.snapshot.clinic.id} onChange={e=>{if(['recording','paused','requesting','saving'].includes(rec.status)){w.notify('Finish the voice note before switching clinics.');return}w.switchIdentity(e.target.value,w.snapshot!.clinics.find(c=>c.id===e.target.value)?.member_id||e.target.value+'-vet')}}>{w.snapshot.clinics.map(c=><option key={c.id} value={c.id}>{c.data.name}</option>)}</select></div><div className="top-right"><span className="local-label">{w.snapshot.mode==='password'?'Connected workspace · sample data':'Local workspace · sample data'}</span>{w.offline?<Badge tone="amber"><WifiSlash/> Offline</Badge>:<span className="saved-indicator"><CheckCircle size={15}/> {w.snapshot.mode==='password'?'Synced':'Saved locally'}</span>}</div></header>
 {w.offline&&<div role="status" className="sync-strip"><WifiSlash size={16}/><span>Offline · saved clinic copy{w.cachedAt?' from '+new Date(w.cachedAt).toLocaleString('en-SG'):''}. Typed notes and voice notes stay on this device until you reconnect. Server actions are unavailable.</span></div>}
 {!w.offline&&w.error&&<div role="alert" className="sync-strip">{w.error}</div>}
 {w.pending.length>0&&<div className="sync-strip"><WarningCircle size={16}/>{w.pending.length} note{w.pending.length!==1?'s':''} waiting to sync. <button onClick={()=>navigate('Settings')}>Review queue</button></div>}
 {['recording','paused','saving'].includes(rec.status)&&<button className="recording-strip" onClick={()=>navigate('Consultation',rec.consultationId)}><Microphone size={16}/>{rec.status==='paused'?'Paused':'Recording'} · {w.records.find(r=>r.id===rec.patientId)?.data.name} · {Math.floor(rec.elapsed/60)}:{String(rec.elapsed%60).padStart(2,'0')}<span>Return to voice note <ArrowRight size={15}/></span></button>}
 <main id="main" tabIndex={-1}><div className="page-heading"><div className="breadcrumb">Clinic / {page==='Patient'?'Patient record':page==='Consultation'?'Consultation':active}</div><div className="global-search"><MagnifyingGlass size={17}/><input aria-label="Search all patients" placeholder="Find a patient or owner" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd>{search&&<div className="search-results">{matches.length?matches.map(p=><button key={p.id} onClick={()=>navigate('Patient',p.id)}><PatientMark patient={p}/><span><strong>{p.data.name}</strong><small>{p.data.breed} · {w.records.find(r=>r.id===p.data.owner_id)?.data.name}</small></span><ArrowUpRight size={16}/></button>):<p>No patients match “{search}”.</p>}</div>}</div></div>
 {(page==='Home'||!page)&&<Dashboard/>}{page==='Appointments'&&<Calendar/>}{page==='Clients'&&<Clients/>}{page==='Handover'&&<Handover/>}{page==='Patients'&&(w.offline?<Patients/>:<PatientBrowser/>)}{page==='Patient'&&<PatientDetail id={id}/>} {page==='Consultation'&&<Consultation key={id} id={id}/>} {page==='Billing'&&<Billing/>}{page==='Inventory'&&<Inventory/>}{page==='Templates'&&<Templates/>}{page==='Messages'&&<Messages/>}{page==='Reports'&&<Reports/>}{page==='Settings'&&<Settings/>}
 </main><footer className="workspace-footer"><span>Broby clinic workspace</span><span>Clinical decisions stay with you.</span></footer></div>{w.toast&&<div role="status" className="toast"><CheckCircle size={18}/>{w.toast}</div>}{assistant&&<Assistant key={w.snapshot.clinic.id+':'+w.snapshot.actor.id} patientId={patientId} onClose={()=>setAssistant(false)}/>}</div>
}
