'use client';
import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Plus,CalendarBlank,CheckCircle,WarningCircle,Users,FileText} from '@phosphor-icons/react';
import {useWorkspace} from '@/lib/workspace';
import {api} from '@/lib/api';
import {Row,today} from '@/lib/types';
import {Badge,BusyButton,Empty,Form,Modal,patientOptions,SourceModal} from './ui';
import {navigate} from './App';
const dateString=(date:Date)=>date.toLocaleDateString('en-CA');
const dateAt=(s:string)=>new Date(s+'T12:00:00');
export function Calendar(){
 const w=useWorkspace();const [date,setDate]=useState(today()),[view,setView]=useState('Week'),[clinician,setClinician]=useState(''),[editing,setEditing]=useState<Row|null>(null),[adding,setAdding]=useState(false),[slot,setSlot]=useState(today());
 const members=w.records.filter(r=>r.kind==='member'&&r.data.active),apps=w.records.filter(r=>r.kind==='appointment'&&(!clinician||r.data.clinician===clinician));
 let start=dateAt(date),days=1;if(view==='Week'){start.setDate(start.getDate()-(start.getDay()+6)%7);days=7}if(view==='Month'){start.setDate(1);start.setDate(start.getDate()-(start.getDay()+6)%7);days=42}
 const dates=Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return dateString(d)});
 const shift=(n:number)=>{const d=dateAt(date);if(view==='Month')d.setMonth(d.getMonth()+n);else d.setDate(d.getDate()+n*(view==='Week'?7:1));setDate(dateString(d))};
 return <><div className="title-row"><div><h1>Appointments</h1><p>Schedule, reschedule and see the week across your team.</p></div><button className="primary" onClick={()=>{setSlot(date);setAdding(true)}}><Plus size={17}/> Schedule appointment</button></div><section className="panel"><div className="panel-heading calendar-toolbar"><div className="tabs">{['Day','Week','Month'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</div><div className="actions"><button className="icon" aria-label="Previous calendar period" onClick={()=>shift(-1)}><ArrowLeft size={17}/></button><input aria-label="Calendar date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="icon" aria-label="Next calendar period" onClick={()=>shift(1)}><ArrowRight size={17}/></button><select aria-label="Filter clinician" value={clinician} onChange={e=>setClinician(e.target.value)}><option value="">All clinicians</option>{members.map(m=><option value={m.id} key={m.id}>{m.data.name}</option>)}</select></div></div><div className={'calendar-grid '+view.toLowerCase()}>{dates.map(d=><section key={d} className={'calendar-cell '+(d===today()?'today':'')}><button className="calendar-date" onClick={()=>{setSlot(d);setAdding(true)}}>{dateAt(d).toLocaleDateString('en-SG',{weekday:'short',day:'numeric',month:'short'})}<Plus size={13}/></button>{apps.filter(a=>a.data.date===d).sort((a,b)=>a.data.time.localeCompare(b.data.time)).map(a=><button className={'calendar-event '+(a.data.status==='cancelled'?'cancelled':'')} key={a.id} onClick={()=>setEditing(a)}><strong>{a.data.time} · {w.records.find(p=>p.id===a.data.patient_id)?.data.name}</strong><span>{a.data.reason}</span><small>{members.find(m=>m.id===a.data.clinician)?.data.name} · {a.data.duration} min</small><Badge tone={a.data.status==='completed'?'teal':'neutral'}>{a.data.status}</Badge></button>)}</section>)}</div></section>
 {(adding||editing)&&<Modal title={editing?'Reschedule appointment':'Schedule appointment'} onClose={()=>{setAdding(false);setEditing(null)}}><Form submit={editing?'Save appointment':'Schedule'} fields={[{name:'patient_id',label:'Patient',required:true,value:editing?.data.patient_id,options:patientOptions(w.records),wide:true},{name:'date',label:'Date',required:true,type:'date',value:editing?.data.date||slot},{name:'time',label:'Time',required:true,type:'time',value:editing?.data.time||'09:00'},{name:'duration',label:'Minutes',type:'number',value:editing?.data.duration||30,min:5},{name:'clinician',label:'Clinician',value:editing?.data.clinician||members.find(m=>m.data.role==='vet')?.id,options:members.map(m=>({value:m.id,label:m.data.name})),required:true},{name:'reason',label:'Reason',required:true,value:editing?.data.reason,wide:true},...(!editing?[{name:'count',label:'Occurrences',type:'number',value:1,min:1},{name:'interval_days',label:'Days between visits',type:'number',value:7,min:1}]:[])]} onSubmit={async p=>{await w.act(editing?'appointment.reschedule':Number(p.count)>1?'appointment.series':'appointment.create',{...p,...(editing?{id:editing.id,version:editing.version}:{})});setAdding(false);setEditing(null);w.notify('Schedule updated')}}/>{editing&&<div className="modal-body"><div className="actions"><button className="secondary" onClick={()=>navigate('Patient',editing.data.patient_id)}>Patient record</button><BusyButton onClick={async()=>{await w.act('appointment.update',{id:editing.id,version:editing.version,status:'cancelled'});setEditing(null)}}>Cancel appointment</BusyButton></div></div>}</Modal>}</>
}
export function Clients(){const w=useWorkspace();const [search,setSearch]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<Row|null>(null),[merge,setMerge]=useState<Row|null>(null);const owners=w.records.filter(r=>r.kind==='owner'&&!r.data.merged_into&&(r.data.name+' '+r.data.email+' '+r.data.phone).toLowerCase().includes(search.toLowerCase()));return <><div className="title-row"><div><h1>Clients</h1><p>Contact details and all animals linked to each owner.</p></div><button className="primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={16}/> Add client</button></div><section className="panel"><div className="panel-heading"><h2>{owners.length} clients</h2><input aria-label="Search clients" placeholder="Name, phone or email" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Client</th><th>Contact</th><th>Patients</th><th/></tr></thead><tbody>{owners.map(o=><tr key={o.id}><td><strong>{o.data.name}</strong></td><td>{o.data.phone||'No phone'}<small>{o.data.email}</small></td><td><div className="actions">{w.records.filter(p=>p.kind==='patient'&&p.data.owner_id===o.id).map(p=><button key={p.id} className="text-button" onClick={()=>navigate('Patient',p.id)}>{p.data.name} · {p.data.species}</button>)}</div></td><td><div className="actions"><button className="secondary small" onClick={()=>{setEditing(o);setModal(true)}}>Edit</button>{w.snapshot?.actor.data.role==='admin'&&<button className="text-button" onClick={()=>setMerge(o)}>Merge duplicate</button>}</div></td></tr>)}</tbody></table></div></section>{modal&&<Modal title={editing?'Edit client':'New client'} onClose={()=>setModal(false)}><Form fields={[{name:'name',label:'Name',required:true,value:editing?.data.name,wide:true},{name:'phone',label:'Phone',value:editing?.data.phone},{name:'email',label:'Email',type:'email',value:editing?.data.email}]} onSubmit={async p=>{await w.act(editing?'owner.update':'owner.create',{...p,...(editing?{id:editing.id,version:editing.version}:{})});setModal(false);w.notify('Client saved')}}/></Modal>}{merge&&<Modal title={'Merge duplicate · '+merge.data.name} onClose={()=>setMerge(null)}><div className="modal-body"><p>Move this client’s patient links to the client selected below. The original owner record is retained in history. Use this only for confirmed duplicates.</p></div><Form fields={[{name:'target_id',label:'Keep this client',required:true,wide:true,options:owners.filter(o=>o.id!==merge.id).map(o=>({value:o.id,label:o.data.name+' · '+(o.data.email||o.data.phone||o.id.slice(0,8))}))}]} submit="Merge patient links" onSubmit={async p=>{await w.act('owner.merge',{...p,id:merge.id,version:merge.version});setMerge(null);w.notify('Duplicate client merged')}}/></Modal>}</>}
export function Handover(){const w=useWorkspace();const [data,setData]=useState<any>(null),[source,setSource]=useState<Row|null>(null);useEffect(()=>{void api('/handover').then(setData).catch(e=>w.notify(e.message))},[w.snapshot]);if(!data)return <Empty title="Loading handover…"/>;return <><div className="title-row"><div><h1>Morning handover</h1><p>{data.date} · Current clinic records, ready for the next shift.</p></div><BusyButton onClick={async()=>{const r=await w.act('reminder.queue_due',{});w.notify(`${r.count} reminder drafts queued for review`)}}>Prepare due reminders</BusyButton></div><div className="metric-grid four">{[['Appointments',data.appointments.length],['Owner submissions',data.intakes.length],['Reminders due',data.reminders.length],['Messages awaiting delivery',data.messages.length]].map(([label,count])=><div className="metric" key={label}><span>{label}</span><strong>{count}</strong></div>)}</div><section className="panel"><div className="panel-heading"><h2>Owner submissions</h2><Badge>{data.intakes.length} new</Badge></div><div className="document-list">{data.intakes.map((r:Row)=><article className="intake-card" key={r.id}><div className="section-heading"><h3>{w.records.find(p=>p.id===r.data.patient_id)?.data.name}</h3>{r.data.urgent&&<Badge tone="amber"><WarningCircle size={14}/> Owner flagged urgent</Badge>}</div><p className="preserve">{r.data.text}</p><div className="actions"><BusyButton className="primary" onClick={async()=>{await w.act('intake.accept',{id:r.id,version:r.version});w.notify('Owner report added as a source')}}><CheckCircle size={16}/> Accept into record</BusyButton><BusyButton onClick={async()=>{await w.act('intake.close',{id:r.id,version:r.version});w.notify('Submission closed')}}>Close</BusyButton><button className="text-button" onClick={()=>navigate('Patient',r.data.patient_id)}>Open patient</button></div></article>)}{!data.intakes.length&&<Empty title="No unreviewed owner submissions"/>}</div></section><div className="reports-grid section-gap">{[['Unfinished consultations',data.unfinished,'Consultation'],['Low stock',data.low_stock,'Inventory'],['Reminders due',data.reminders,'Messages'],['Message drafts',data.messages,'Messages']].map(([title,items,page]:any)=><section className="panel" key={title}><div className="panel-heading"><h2>{title}</h2><Badge>{items.length}</Badge></div><div className="document-list">{items.map((r:Row)=><button key={r.id} className="visit-row" onClick={()=>page==='Consultation'?navigate(page,r.id):navigate(page)}><FileText size={18}/><span><strong>{r.data.title||r.data.name||r.data.recipient}</strong><small>{w.records.find(p=>p.id===r.data.patient_id)?.data.name||r.data.stock+' '+r.data.unit}</small></span><ArrowRight size={16}/></button>)}{!items.length&&<p className="muted">Nothing waiting.</p>}</div></section>)}</div>{source&&<SourceModal source={source} onClose={()=>setSource(null)}/>}</>}
