'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {useWorkspace} from '@/lib/workspace';
import {Row} from '@/lib/types';
import {Form} from './ui';
export function ObservationForm({patientId,onDone}:{patientId:string;onDone:()=>void}){const w=useWorkspace();const [terms,setTerms]=useState<any[]>([]),[code,setCode]=useState('weight');useEffect(()=>{void api('/ontology').then(setTerms).catch(e=>w.notify(e.message))},[]);const term=terms.find(t=>t.code===code);if(!term)return <div className="modal-body">Loading observation definitions…</div>;return <><div className="modal-body"><label>Observation type<select value={code} onChange={e=>setCode(e.target.value)}>{terms.map(t=><option key={t.code} value={t.code}>{t.name} · {t.category}</option>)}</select></label></div><Form key={code} fields={[{name:'value',label:term.name+(term.unit?' ('+term.unit+')':''),required:true,type:term.value_type==='number'?'number':'textarea',step:'any',...(term.value_type==='boolean'?{type:'text',options:[{value:'true',label:'Yes / present'},{value:'false',label:'No / absent'}]}:{}),wide:true},...(term.value_type==='number'?[{name:'low',label:'Reference minimum',type:'number',step:'any'},{name:'high',label:'Reference maximum',type:'number',step:'any'}]:[]),{name:'source_id',label:'Original source',required:true,wide:true,options:w.records.filter(r=>r.kind==='source'&&r.data.patient_id===patientId).map(r=>({value:r.id,label:r.data.title}))}]} onSubmit={async p=>{await w.act('observation.record',{...p,patient_id:patientId,code});onDone();w.notify('Source-linked observation saved')}}/></>}
export function ObservationTrend({records,onSource}:{records:Row[];onSource:(id:string)=>void}){const numeric=records.filter(r=>typeof r.data.value==='number');const names=Array.from(new Set(numeric.map(r=>r.data.name+' ('+r.data.unit+')')));const [chosen,setChosen]=useState('');const name=names.includes(chosen)?chosen:names[0];const points=numeric.filter(r=>r.data.name+' ('+r.data.unit+')'===name).sort((a,b)=>a.created_at.localeCompare(b.created_at));if(!points.length)return null;const values=points.map(p=>p.data.value);const low=Math.min(...values),high=Math.max(...values),span=high-low||1;const xy=points.map((p,i)=>({r:p,x:45+(points.length===1?.5:i/(points.length-1))*540,y:145-(p.data.value-low)/span*95}));return <section className="observation-trend"><div className="section-heading"><h3>Recorded trend</h3><select aria-label="Observation trend" value={name} onChange={e=>setChosen(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></div><svg viewBox="0 0 640 200" role="img" aria-label={name+' recorded values over time'}><line x1="45" y1="160" x2="585" y2="160" stroke="#d7dbd2"/><polyline points={xy.map(p=>p.x+','+p.y).join(' ')} fill="none" stroke="#288b7e" strokeWidth="2"/>{xy.map(p=><g key={p.r.id} onClick={()=>onSource(p.r.data.source_id)} style={{cursor:'pointer'}}><circle cx={p.x} cy={p.y} r="5" fill="#288b7e"/><text x={p.x} y={p.y-13} textAnchor="middle" fontSize="12" fill="currentColor">{p.r.data.value}</text><title>{p.r.data.name}: {p.r.data.value} {p.r.data.unit}. {new Date(p.r.created_at).toLocaleDateString('en-SG')}</title></g>)}<text x="45" y="184" fontSize="11" fill="#73776f">{new Date(points[0].created_at).toLocaleDateString('en-SG')}</text><text x="585" y="184" textAnchor="end" fontSize="11" fill="#73776f">{new Date(points.at(-1)!.created_at).toLocaleDateString('en-SG')}</text></svg><p className="muted">{points.length} measured value{points.length===1?'':'s'} · source receipts below. Values are not clinical interpretations.</p></section>}

export function LabImport({patientId,onDone}:{patientId:string;onDone:()=>void}){const w=useWorkspace();return <Form submit="Import source and results" fields={[{name:'title',label:'Report title / laboratory reference',required:true,wide:true},{name:'csv',label:'CSV results',type:'textarea',required:true,wide:true,placeholder:'name,value,unit,low,high\nCreatinine,1.2,mg/dL,0.8,2.4'}]} onSubmit={async p=>{const r=await w.act('lab.import',{...p,patient_id:patientId});w.notify(r.count+' results imported with the original CSV receipt');onDone()}}><p className="integration-note">Paste numeric results exactly as provided by the laboratory. Columns: name, value, unit, low, high. Reference limits are optional. Values are not converted or interpreted. All rows must validate before any result is saved.</p></Form>}
