'use client';
import React,{useEffect,useState} from 'react';
import {api,headers} from '@/lib/api';
import {useWorkspace} from '@/lib/workspace';
import {Row} from '@/lib/types';
import {Badge,BusyButton,Modal} from './ui';
type Status='retain'|'wrong_patient'|'unresolved';
type Choice={group_key:string;disposition:Status;reason:string;record_decisions:{id:string;disposition:Status;reason:string}[]};
function Original({row}:{row:Row}){return <article className="source-quote"><Badge tone="amber">Historical original · verify identity</Badge><h4>{row.data.title||row.data.name||row.kind}</h4><p>{row.kind} · {row.id} · revision {row.version}</p><p className="preserve">{row.data.text||row.data.body||''}</p><details><summary>All preserved fields</summary><pre className="receipt-text">{JSON.stringify(row.data,null,2)}</pre></details></article>}
function Review({id,onClose}:{id:string;onClose:()=>void}){
 const w=useWorkspace(),[review,setReview]=useState<any>(null),[error,setError]=useState(''),[choices,setChoices]=useState<Record<string,Choice>>({}),[confirm,setConfirm]=useState(false),[hold,setHold]=useState(false),[media,setMedia]=useState<{url:string;audio:boolean}|null>(null);
 const load=async()=>{setReview(null);setChoices({});setConfirm(false);setHold(false);setError('');try{setReview(await api('/clinical-reconciliation/'+id))}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load()},[id]);useEffect(()=>()=>{if(media)URL.revokeObjectURL(media.url)},[media]);
 const change=(g:any,patch:Partial<Choice>)=>setChoices(c=>({...c,[g.group_key]:{...(c[g.group_key]||{group_key:g.group_key,disposition:'unresolved',reason:'',record_decisions:[]}),...patch}}));
 const openMedia=async(row:Row)=>{const r=await fetch('/api/clinical-reconciliation/'+id+'/media/'+row.id+'?acknowledge_historical=true',{headers:headers()});if(!r.ok)throw new Error('Historical media unavailable. Refresh this review.');setMedia({url:URL.createObjectURL(await r.blob()),audio:row.kind==='recording'})};
 const valid=Object.values(choices).length>0&&Object.values(choices).every(c=>c.reason.trim().length>=10&&c.record_decisions.length===review?.groups.find((g:any)=>g.group_key===c.group_key)?.records.length&&c.record_decisions.every(r=>r.disposition===c.disposition&&r.reason.trim().length>=10));
 return <Modal title="Clinician identity reconciliation" onClose={onClose} wide><div className="modal-body"><p className="inline-notice">Review original evidence and each receiving record. A disposition never moves, edits, deletes or declares clinical facts equivalent. Missing provenance stays unresolved.</p><BusyButton onClick={load}>Reload complete review and discard choices</BusyButton>{error&&<p role="alert" className="error">{error}</p>}{!review&&!error&&<p role="status">Loading complete history…</p>}{review&&<>
  <div className="form-grid">{review.identities.map((v:any,i:number)=><section key={v.patient.id}><h3>{i?'Corrected receiving patient':'Previous receiving patient'}</h3><strong>{v.patient.data.name} · {v.patient.data.species}</strong><p>{v.patient.id}</p><p>Owners: {v.owners.map((o:Row)=>o.data.name+' ('+o.id+')').join(', ')}</p><details><summary>Preserved identity and complete history</summary><pre className="receipt-text">{JSON.stringify(v.patient.data,null,2)}</pre>{v.history.existing_records.map((r:Row)=><Original key={r.id} row={r}/>)}</details></section>)}</div>
  <section className="inline-notice"><h3>Effect of a wrong-patient or unresolved disposition</h3><p>{review.patient_hold_preview.policy}</p><p>Retain a complete group only after independent clinician verification. Later identity or record changes reopen its hold. This screen cannot release a patient hold, clear missing provenance or settle another clinic’s copies.</p></section>
  <details><summary>Mapping correction and immutable clinician receipts</summary><pre className="receipt-text">{JSON.stringify({correction:review.correction,decisions:review.decisions},null,2)}</pre></details>
  {review.groups.map((g:any)=>{const choice=choices[g.group_key];return <section className="panel" key={g.group_key}><h3>{g.origin.kind} · {review.identities.find((v:any)=>v.patient.id===g.patient_id)?.patient.data.name}</h3><p>Receiving patient: {g.patient_id}</p><p>Source clinic {g.origin.source_clinic} · original {g.origin.origin_id} · revision {g.origin.revision}</p><details><summary>Immutable approved source and receipt</summary><pre className="receipt-text">{JSON.stringify({source:g.origin,media_verification:g.media},null,2)}</pre></details>{g.previous_decision&&<p className="inline-notice">Earlier: {g.previous_decision.disposition}. Reason: {g.previous_decision.reason}. Receipt: {g.previous_decision.receipt_id}</p>}
   <label className="feature-lock"><input type="checkbox" checked={!!choice} onChange={e=>{if(e.target.checked)change(g,{});else setChoices(c=>{const next={...c};delete next[g.group_key];return next})}}/> Include this complete origin group</label>
   {choice&&<div className="form"><label htmlFor={'reconcile-disposition-'+g.group_key}>Group disposition</label><select id={'reconcile-disposition-'+g.group_key} value={choice.disposition} onChange={e=>change(g,{disposition:e.target.value as Status,record_decisions:[]})}><option value="unresolved">Unresolved · suspend current use</option><option value="wrong_patient">Wrong patient · suspend current use</option><option value="retain">Verified for this patient · retain</option></select><label htmlFor={'reconcile-reason-'+g.group_key}>Group reasoning<textarea id={'reconcile-reason-'+g.group_key} maxLength={1000} value={choice.reason} onChange={e=>change(g,{reason:e.target.value})}/></label></div>}
   {g.records.map((row:Row)=>{const item=choice?.record_decisions.find(x=>x.id===row.id);return <div key={row.id}><Original row={row}/>{['attachment','recording'].includes(row.kind)&&<BusyButton disabled={w.offline} onClick={()=>openMedia(row)}>Open preserved historical {row.kind==='recording'?'audio':'file'}</BusyButton>}{choice&&<div className="form"><label className="feature-lock"><input type="checkbox" checked={!!item} onChange={e=>change(g,{record_decisions:e.target.checked?[...choice.record_decisions,{id:row.id,disposition:choice.disposition,reason:''}]:choice.record_decisions.filter(x=>x.id!==row.id)})}/> I reviewed this individual record as {choice.disposition.replaceAll('_',' ')}</label>{item&&<label htmlFor={'reconcile-record-reason-'+row.id}>Reason for this individual record<textarea id={'reconcile-record-reason-'+row.id} maxLength={1000} value={item.reason} onChange={e=>change(g,{record_decisions:choice.record_decisions.map(x=>x.id===row.id?{...x,reason:e.target.value}:x)})}/></label>}</div>}</div>})}</section>})}
  <section><h3>Unresolved history without a complete origin group</h3><p>{review.unresolved_legacy_records.length} records remain outside this workflow. No equivalence or resolution can be recorded for these records.</p><details><summary>Inspect preserved unresolved records</summary>{review.unresolved_legacy_records.map((r:Row)=><Original key={r.id} row={r}/>)}</details></section>
  <section><h3>Known onward copies</h3>{review.known_onward_copies.length?review.known_onward_copies.map((copy:any,i:number)=><p key={i}>Clinic {copy.target_clinic} · patient {copy.target_patient_id||'unavailable'} · copy {copy.target_id} · transfer {copy.request_id}. If a linked source patient is held, separate receiving-clinic review is required; this review never corrects that copy.</p>):<p>No onward copies with recorded lineage found. Downloaded, offline or untracked copies may still exist.</p>}</section>
  <ul>{review.limitations.map((t:string)=><li key={t}>{t}</li>)}</ul>
  <label className="feature-lock"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> I reviewed both identities, the approved source, and every selected individual record with its own reason.</label><label className="feature-lock"><input type="checkbox" checked={hold} onChange={e=>setHold(e.target.checked)}/> I understand the patient-level hold, unresolved derivatives, onward copies, and downloaded/offline limitations.</label>
  <BusyButton className="primary" disabled={!valid||!confirm||!hold||w.offline} onClick={async()=>{await w.act('clinical.reconcile',{correction_id:id,expected_digest:review.digest,confirm_review:true,acknowledge_patient_hold:true,decisions:Object.values(choices)},'clinical-reconcile:'+review.digest);w.notify('Dispositions recorded. Originals preserved; unresolved history stays restricted.');await load()}}>Record clinician dispositions</BusyButton>
 </>}{media&&<section className="inline-notice"><h3>Historical original · not current clinical advice</h3>{media.audio?<audio controls src={media.url}/>:<iframe className="source-document" title="Preserved historical file" src={media.url}/>}<button className="secondary" onClick={()=>setMedia(null)}>Close historical media</button></section>}</div></Modal>;
}
function ForensicHistory({patientId,onClose}:{patientId:string;onClose:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[media,setMedia]=useState<{url:string;audio:boolean}|null>(null);
 useEffect(()=>{let live=true;void api('/clinical-reconciliation/patients/'+patientId+'/history').then(result=>{if(live)setData(result)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[patientId]);
 useEffect(()=>()=>{if(media)URL.revokeObjectURL(media.url)},[media]);
 return <Modal title="Qualified historical evidence" onClose={onClose} wide><div className="modal-body"><p role="alert" className="inline-notice">Historical evidence only. This does not verify identity, approve clinical use or settle independent receiving copies.</p>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Loading preserved history…</p>}{data&&<><h3>{data.patient.data.name} · {patientId}</h3><p>{data.limitation}</p><details><summary>Exact affected records and source-review references</summary><pre className="receipt-text">{JSON.stringify(data.qualifications,null,2)}</pre></details>{data.records.map((row:Row)=><div key={row.id}><Original row={row}/>{['attachment','recording'].includes(row.kind)&&<BusyButton onClick={async()=>{const response=await fetch('/api/clinical-reconciliation/patients/'+patientId+'/media/'+row.id+'?acknowledge_historical=true',{headers:headers()});if(!response.ok)throw new Error('Historical media is unavailable.');setMedia({url:URL.createObjectURL(await response.blob()),audio:row.kind==='recording'})}}>Open historical original</BusyButton>}</div>)}</>}{media&&<section className="inline-notice"><h3>Historical original · not current clinical advice</h3>{media.audio?<audio controls src={media.url}/>:<iframe className="source-document" title="Historical original" src={media.url}/>}<button onClick={()=>setMedia(null)}>Close historical media</button></section>}</div></Modal>;
}
export function ClinicalReconciliation({patientId}:{patientId:string}){
 const w=useWorkspace(),[open,setOpen]=useState(''),[archive,setArchive]=useState(false),patient=w.records.find(r=>r.id===patientId&&r.kind==='patient');const held=patient?.data.clinical_reconciliation;
 const corrections=w.records.filter(r=>r.kind==='transfer_mapping_correction'&&(r.data.patient_id===patientId||r.data.previous_patient_id===patientId));
 if(!corrections.length&&!held)return null;
 return <><section className="panel" role="status"><h3>{held?'Current clinical use is on hold':'Historical patient identity needs clinician review'}</h3><p>{held?'Clinical history, owner media, approval, export and AI use are restricted because identity or derivative provenance is unresolved. Originals remain in the qualified review.':'A patient-link correction preserves both histories. Clinical equivalence and historical reconciliation remain unresolved.'}</p><p>Known onward copies need their receiving clinic’s review. Previous downloaded or offline copies cannot be recalled. Reconnect and refresh before a clinical action.</p>{corrections.map(r=><div key={r.id}><p>Mapping correction: {r.id} · {r.data.reason}</p>{w.snapshot?.permissions.includes('clinical.reconcile')&&<button className="secondary" disabled={w.offline} onClick={()=>setOpen(r.id)}>Review original evidence and dispositions</button>}</div>)}{held&&w.snapshot?.permissions.includes('clinical.reconcile')&&<button className="secondary" disabled={w.offline} onClick={()=>setArchive(true)}>Open qualified preserved history</button>}{held&&!corrections.length&&<p>This receiving copy is affected by a source-clinic dispute. Keep it unresolved and arrange a separate receiving-clinic review.</p>}</section>{open&&<Review id={open} onClose={()=>setOpen('')}/>} {archive&&<ForensicHistory patientId={patientId} onClose={()=>setArchive(false)}/>}</>;
}
