'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {useWorkspace} from '@/lib/workspace';
import {Badge,BusyButton,Form,Modal} from './ui';

export function OrganizationAdoption({organization,onComplete}:{organization:any;onComplete:()=>Promise<void>}){
 const w=useWorkspace();
 return <AdoptionPanel key={w.snapshot?.clinic.id+':'+w.snapshot?.actor.id} organization={organization} onComplete={onComplete}/>;
}
function AccessReview({consent}:{consent:any}){
 return <><h3>{consent.clinic_name} → {consent.organization_name}</h3><p>{consent.timezone} · {consent.currency}</p><p>{consent.access}</p><p>Records, balances, stock, settings and patient identities stay in this clinic. Joining does not merge patients or change existing staff memberships. The master can manage the clinic after approval.</p><p>Inherited restrictions: {consent.locked_actions.length?consent.locked_actions.map((x:string)=>x.replaceAll('.',' ').replaceAll('_',' ')).join(', '):'None currently'}. The master can change organization restrictions later.</p></>;
}
function AdoptionPanel({organization,onComplete}:{organization:any;onComplete:()=>Promise<void>}){
 const w=useWorkspace(),[requests,setRequests]=useState<any[]>([]),[error,setError]=useState(''),[proposal,setProposal]=useState<any>(null),[review,setReview]=useState<any>(null);
 useEffect(()=>{let active=true;void api('/organization/adoptions').then(r=>{if(active){setRequests(r);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[w.snapshot]);
 return <section className="section-gap" aria-label="Existing clinic adoption"><h3>Join an existing clinic to an organization</h3>{organization?.master&&<p>Give the independent clinic administrator this organization ID: <code>{organization.id}</code>. They must review access and request to join from their own clinic. After adding a new membership, sign out and sign in again to verify it for encrypted offline work.</p>}
 {!organization&&<Form submit="Review organization access" fields={[{name:'organization_id',label:'Organization ID supplied by its master',required:true}]} onSubmit={async p=>setProposal(await api('/organization/join-preview',{method:'POST',body:JSON.stringify(p)}))}/>}
 {error&&<p role="alert" className="error">{error}</p>}{!requests.length&&<p>No clinic adoption requests.</p>}{requests.map(r=><article className="history-entry" key={r.id}><h4>{r.data.consent.clinic_name} → {r.data.consent.organization_name}</h4><Badge>{r.data.status}</Badge><p>{r.data.reason}</p><p>Requested {new Date(r.data.requested_at).toLocaleString()} · expires {new Date(r.data.expires_at).toLocaleString()}</p>{r.data.decision_reason&&<p>Decision: {r.data.decision_reason}</p>}{r.data.status==='pending'&&(organization?.master?<><BusyButton onClick={async()=>setReview(await api('/organization/adoption-preview',{method:'POST',body:JSON.stringify({id:r.id,version:r.version})}))}>Review clinic adoption</BusyButton><details><summary>Decline request</summary><Form submit="Decline adoption" fields={[{name:'reason',label:'Reason for declining',required:true}]} onSubmit={async p=>{await w.act('organization.join_review',{id:r.id,version:r.version,decision:'declined',reason:p.reason});await onComplete()}}/></details></>:<Form submit="Withdraw request" fields={[{name:'reason',label:'Reason for withdrawing',required:true}]} onSubmit={async p=>{await w.act('organization.join_cancel',{id:r.id,version:r.version,reason:p.reason});await onComplete()}}/>)}</article>)}
 {proposal&&<Modal title="Review organization access" onClose={()=>setProposal(null)} wide><div className="modal-body"><AccessReview consent={proposal}/><p>The organization master will receive this clinic name, settings summary, administrative reason and record counts for review. They receive access to all clinic data only after accepting. The request expires after seven days.</p></div><Form submit="Request to join organization" fields={[{name:'reason',label:'Administrative reason',required:true,type:'textarea'}]} onSubmit={async p=>{await w.act('organization.join_request',{organization_id:proposal.organization_id,digest:proposal.digest,accept_access:p.accept_access==='on',reason:p.reason});setProposal(null);await onComplete();w.notify('Request saved. No access has been granted yet.')}}><label><input type="checkbox" name="accept_access" required/>I authorize the displayed master access and inherited restrictions for this clinic.</label></Form></Modal>}
 {review&&<Modal title="Accept existing clinic" onClose={()=>setReview(null)} wide><div className="modal-body"><AccessReview consent={review.data.consent}/><p>Clinic administrator’s reason: {review.data.reason}</p><h4>Current workspace record counts</h4><p>{Object.entries(review.record_counts).map(([kind,count])=>`${kind.replaceAll('_',' ')}: ${count}`).join(' · ')}</p></div><Form submit="Accept clinic into organization" fields={[{name:'reason',label:'Acceptance reason',required:true,type:'textarea'}]} onSubmit={async p=>{await w.act('organization.join_review',{id:review.id,version:review.version,digest:review.digest,decision:'accepted',accept_access:p.accept_access==='on',reason:p.reason});setReview(null);await onComplete();w.notify('Clinic joined. Sign out and sign in again to enable encrypted offline work in the new clinic.')}}><label><input type="checkbox" name="accept_access" required/>I reviewed this clinic, its record counts and the access and restrictions above.</label></Form></Modal>}
 </section>;
}
