'use client';
import {useEffect,useState} from 'react';
import {useWorkspace} from '@/lib/workspace';
import {api} from '@/lib/api';
import {Badge,Form,BusyButton} from './ui';
import {ClinicalEscalations} from './ClinicalEscalations';

export function OwnerConversationQueue(){
 const w=useWorkspace(),[id,setId]=useState(''),[thread,setThread]=useState<any>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[replyEpoch,setReplyEpoch]=useState(0);
 const threads=w.records.filter(r=>r.kind==='owner_thread'),policy=w.records.find(r=>r.kind==='owner_policy');
 useEffect(()=>{let live=true;setError('');if(!id){setThread(null);return}void api('/owner-conversations/'+id).then(data=>{if(live)setThread(data)}).catch(e=>{if(live){setError(e.message);setThread(null)}});return()=>{live=false}},[id,revision,w.snapshot?.clinical_verification?.epoch]);
 const stale=!!thread&&w.records.find(r=>r.id===thread.id)?.version!==thread.version;
 const payload=()=>({id:thread.id,version:thread.version,last_owner_turn:thread.data.last_owner_turn});
 return <section className="panel section-gap"><div className="panel-heading"><h2>Owner conversations</h2><Badge>{threads.filter(r=>r.data.status==='needs_attention').length} need review</Badge></div><div className="modal-body"><p>Portal questions and staff replies are saved here. Urgent flags and elapsed acknowledgement targets create internal alerts. External staff notifications require the separately reviewed clinic policy below; saving a portal reply does not send WhatsApp.</p>
 <ClinicalEscalations onReview={value=>{setId(value);setThread(null);setRevision(n=>n+1)}}/>
 <select aria-label="Owner conversation" value={id} onChange={e=>{setId(e.target.value);setThread(null)}}><option value="">Choose a conversation</option>{threads.map(r=><option key={r.id} value={r.id}>{w.records.find(p=>p.id===r.data.patient_id)?.data.name} · {r.data.title} · {r.data.status.replaceAll('_',' ')}</option>)}</select>
 {error&&<p role="alert" className="error">{error}</p>}{thread&&<>{thread.clinical_reconciliation&&<p role="alert" className="inline-notice">Historical evidence only. This patient has unresolved clinical identity; preserved replies and cards are not currently verified instructions.</p>}{stale&&<p role="alert">New activity arrived. Refresh and read the latest conversation before submitting your review.</p>}<BusyButton onClick={async()=>setRevision(n=>n+1)}>Refresh conversation</BusyButton><h3>{thread.clinical_reconciliation?'Owner follow-up · clinical identity review':thread.data.title}</h3><p>{thread.data.status.replaceAll('_',' ')}{thread.data.urgent?' · Owner flagged urgent':''}</p>{thread.data.ack_due_at&&<p>{Date.parse(thread.data.ack_due_at)<Date.now()?'Internal acknowledgement overdue':'Internal acknowledgement target'}: {new Date(thread.data.ack_due_at).toLocaleString()}</p>}{thread.turns.map((t:any)=><article className="intake-card" key={t.id}><strong>{t.data.speaker==='owner'?'Owner':'Clinic'}</strong><small> · {new Date(t.created_at).toLocaleString()}</small><p className="preserve">{t.data.message}</p>{t.data.answer&&<p>{t.data.answer}</p>}{t.data.cards?.map((c:any)=><blockquote key={c.id}><strong>{c.title}</strong><p className="preserve">{c.text}</p><small>Receipt: {c.id} · version {c.version}</small></blockquote>)}</article>)}{thread.data.status!=='closed'&&<>{thread.clinical_reconciliation&&<p className="inline-notice">This question still needs staff follow-up. <a href={'#Patient/'+thread.data.patient_id}>Open patient and owner contact details</a>. Contact the owner through the clinic’s established process and record the review below. New clinical portal replies remain on hold.</p>}{!thread.clinical_reconciliation&&<Form key={'reply-'+thread.id+':'+replyEpoch} submit="Save reply to owner portal" fields={[{name:'message',label:'Clinic reply',type:'textarea',required:true}]} onSubmit={async p=>{if(stale)throw new Error('Refresh and review the latest owner message first.');await w.act('conversation.reply',{...payload(),message:p.message});setReplyEpoch(n=>n+1);setRevision(n=>n+1);w.notify('Reply saved to the owner portal; no external message sent')}}/>}<Form key={'review-'+thread.id} submit="Record conversation review" fields={[{name:'transition',label:'Review action',options:[{value:'acknowledge',label:'Acknowledge for follow-up'},{value:'close',label:'Close after review'}]},{name:'reason',label:'Review reason',required:true}]} onSubmit={async p=>{if(stale)throw new Error('Refresh and review the latest owner message first.');await w.act('conversation.'+p.transition,{...payload(),reason:p.reason});setRevision(n=>n+1);w.notify('Conversation review recorded')}}/></>}</>}
 {w.snapshot?.actor.data.role==='admin'&&<details><summary>Internal acknowledgement target</summary><p>Optional clinic-defined reminder target. This form does not change the separately reviewed external notification policy or promise an emergency response.</p><Form key={policy?.version||0} submit="Save internal target" fields={[{name:'ack_minutes',label:'Minutes until internal alert (blank disables)',type:'number',min:1,value:policy?.data.ack_minutes??''},{name:'reason',label:'Policy reason',required:true}]} onSubmit={async p=>{await w.act('conversation.policy',{version:policy?.version||0,ack_minutes:p.ack_minutes||null,reason:p.reason});w.notify('Internal target saved for future questions')}}/></details>}
 </div></section>;
}
