'use client';
import {useEffect,useRef,useState} from 'react';

export function OwnerConversation({base}:{base:string}){
 const [list,setList]=useState<any[]>([]),[id,setId]=useState(''),[thread,setThread]=useState<any>(null),[message,setMessage]=useState(''),[staff,setStaff]=useState(false),[urgent,setUrgent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef({body:'',key:''}),sequence=useRef(0),initial=useRef(true);
 const request=async(path:string,options?:RequestInit)=>{const r=await fetch(base+'/conversations'+path,options),data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'Could not load this conversation.');return data};
 useEffect(()=>{let live=true;const refresh=async()=>{const n=++sequence.current;try{const rows=await request('');const current=id?await request('/'+id):null;if(live&&n===sequence.current){setList(rows);setThread(current);setError('');if(initial.current){initial.current=false;if(rows.length)setId(rows[0].id)}}}catch(e){if(live&&n===sequence.current){setThread(null);setList([]);setError((e as Error).message)}}};void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>{live=false;sequence.current++;clearInterval(timer)}},[base,id]);
 return <section className="panel"><div className="panel-heading"><h2>Ask the clinic</h2><button className="secondary" disabled={busy} onClick={()=>{sequence.current++;setId('');setThread(null);setMessage('');setStaff(false);setUrgent(false);pending.current={body:'',key:''}}}>New conversation</button></div><div className="form">
 <p>Retrieve approved care instructions or leave a question for staff. Questions and replies are saved here for this pet and private clinic link.</p><p className="integration-note">This chat is not monitored continuously. It cannot assess symptoms or decide whether it is safe to wait. For urgent concerns, contact the clinic or an emergency veterinary service directly.</p>
 <label>Saved conversations<select disabled={busy} value={id} onChange={e=>{sequence.current++;setId(e.target.value);setThread(null);setError('')}}><option value="">New conversation</option>{list.map(r=><option key={r.id} value={r.id}>{r.title} · {r.status.replaceAll('_',' ')}</option>)}</select></label>
 {error&&<p role="alert" className="error">{error}</p>}
 {thread&&<><p role="status">Conversation: {thread.status.replaceAll('_',' ')}{thread.urgent?' · You marked this urgent':''}</p>{thread.turns.map((t:any)=><article className="intake-card" key={t.id}><strong>{t.speaker==='owner'?'You':'Clinic'}</strong><small> · {new Date(t.created_at).toLocaleString()}</small><p className="preserve">{t.message}</p>{t.state!=='completed'&&<p>Retrieval {t.state}. Your question is saved; retry the same question if needed.</p>}{t.answer&&<p>{t.answer}</p>}{t.cards.map((c:any)=><blockquote key={c.id}><strong>{c.title}</strong><p className="preserve">{c.text}</p><small>Shared record · {c.id.slice(0,12)}</small></blockquote>)}{t.changed_sources&&<p>Some earlier shared records changed or were withdrawn. Ask again to retrieve the current approved information.</p>}{t.truncated&&<p>Showing the first 20 records. Open the Records tab for the full shared information.</p>}</article>)}{thread.emergency_phone&&<a href={'tel:'+thread.emergency_phone}>Call clinic: {thread.emergency_phone}</a>}</>}
 {thread?.status==='closed'?<p>This conversation is closed. Start a new conversation for another question.</p>:<form onSubmit={async e=>{e.preventDefault();const body=JSON.stringify({message,thread_id:id||null,request_staff:staff,urgent});if(pending.current.body!==body)pending.current={body,key:crypto.randomUUID()};setBusy(true);setError('');sequence.current++;try{const result=await request('',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(body),key:pending.current.key})});sequence.current++;setThread(result);setId(result.id);setList(await request(''));setMessage('');setStaff(false);setUrgent(false);pending.current={body:'',key:''}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 <label>Your question<textarea disabled={busy} required maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="What medication instructions were shared?"/></label><label className="feature-lock"><input disabled={busy} type="checkbox" checked={staff} onChange={e=>setStaff(e.target.checked)}/> Ask a staff member to review</label><label className="feature-lock"><input disabled={busy} type="checkbox" checked={urgent} onChange={e=>setUrgent(e.target.checked)}/> I want the clinic to know this is urgent</label><button className="primary" disabled={busy}>{busy?'Saving question…':'Save question'}</button></form>}
 </div></section>;
}
