'use client';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {api,headers} from '@/lib/api';
import {useWorkspace} from '@/lib/workspace';
import {PatientV2,PatientEvent,Receipt,Series} from '@/lib/spine';
import {Modal,Empty,Badge} from './ui';
import {navigate} from './App';

function Failure({message,retry}:{message:string;retry:()=>void}){return <div role="alert" className="spine-state"><p>{message}</p><button className="secondary" onClick={retry}>Try again</button></div>}
function usePage<T>(path:string,revision=''){
 const clinic=useWorkspace().snapshot?.clinic.id;
 const [items,setItems]=useState<T[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const sequence=useRef(0),busy=useRef(false),sentinel=useRef<HTMLDivElement>(null);
 const read=useCallback(async(next:string|null=null)=>{if(next&&busy.current)return;const n=++sequence.current;busy.current=true;setLoading(true);setError('');try{const result=await api(path+(next?'&cursor='+encodeURIComponent(next):''));if(n===sequence.current){setItems(old=>next?[...old,...result.items]:result.items);setCursor(result.next_cursor)}}catch(e){if(n===sequence.current)setError((e as Error).message)}finally{if(n===sequence.current){busy.current=false;setLoading(false)}}},[path,clinic,revision]);
 useEffect(()=>{setItems([]);setCursor(null);void read();return()=>{sequence.current++;busy.current=false}},[read]);
 useEffect(()=>{if(!cursor||error||loading)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))void read(cursor)},{rootMargin:'160px'});if(sentinel.current)observer.observe(sentinel.current);return()=>observer.disconnect()},[cursor,error,loading,read]);
 return {items,cursor,loading,error,sentinel,retry:()=>void read(items.length?cursor:null),refresh:()=>void read(),more:()=>void read(cursor)};
}
export function PatientBrowser(){
 const [query,setQuery]=useState(''),[q,setQ]=useState('');useEffect(()=>{const t=setTimeout(()=>setQ(query.trim()),200);return()=>clearTimeout(t)},[query]);
 const page=usePage<PatientV2>('/v2/patients?limit=25&q='+encodeURIComponent(q));
 return <><div className="title-row"><div><h1>Patients</h1><p>One record for every animal.</p></div><button className="secondary" onClick={()=>navigate('Home')}>Add patient / start visit</button></div><section className="panel"><div className="panel-heading"><input aria-label="Search patients or owners" placeholder="Search patient or owner name" value={query} onChange={e=>setQuery(e.target.value)}/><span className="mono-label">PATIENT DIRECTORY</span></div><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Species / breed</th><th>Owner</th><th>Last seen</th><th/></tr></thead><tbody>{page.items.map(p=><tr key={p.id}><td><button className="text-button" onClick={()=>navigate('Patient',p.id)}>{p.name}</button></td><td>{p.species} · {p.breed||'—'}</td><td>{p.owner?.name||'Not linked'}</td><td>{p.last_seen?new Date(p.last_seen).toLocaleDateString('en-SG'):'No recorded visit'}</td><td><button className="text-button" aria-label={'Open '+p.name+' '+p.id} onClick={()=>navigate('Patient',p.id)}>Open →</button></td></tr>)}</tbody></table></div>{page.loading&&<p role="status" className="spine-state">Loading patients…</p>}{page.error&&<Failure message={page.error} retry={page.retry}/>} {!page.loading&&!page.error&&!page.items.length&&<Empty title="No matching patients" text="Try another patient or owner name."/>}<div ref={page.sentinel}/>{page.cursor&&!page.loading&&<button className="text-button spine-more" onClick={page.more}>Load more patients</button>}</section></>
}
export function ReceiptView({receipt,onClose}:{receipt:Receipt;onClose:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[url,setUrl]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let live=true,objectUrl='';setData(null);setError('');setUrl('');void api('/v2/sources/'+encodeURIComponent(receipt.receipt_id)).then(async r=>{if(!live)return;setData(r);if(r.content_url){const response=await fetch(r.content_url,{headers:headers()});if(!response.ok)throw new Error('Source file could not be loaded');objectUrl=URL.createObjectURL(await response.blob());if(live)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[receipt.receipt_id,attempt]);
 return <Modal title="Original source" onClose={onClose}><div className="modal-body">{error?<Failure message={error} retry={()=>setAttempt(x=>x+1)}/>:!data?<p role="status">Loading source…</p>:<><Badge>{data.kind}</Badge><h3>{data.title}</h3><p className="muted">{data.id}{data.page?' · Page '+data.page:''}{data.start_ms!=null?' · '+(data.start_ms/1000).toFixed(1)+'–'+((data.end_ms??data.start_ms)/1000).toFixed(1)+' seconds':''}</p>{data.text&&<pre className="receipt-text">{data.text}</pre>}{url&&data.kind==='audio'&&<audio controls src={url} onLoadedMetadata={e=>{e.currentTarget.currentTime=(data.start_ms||0)/1000}}/>}{url&&data.kind==='document'&&<><a href={url+'#page='+(data.page||1)} target="_blank" rel="noreferrer">Open document at page {data.page||1} ↗</a><iframe className="source-document" title="Source document" src={url+'#page='+(data.page||1)}/></>}{!url&&!data.text&&<p>The provenance is recorded, but the original file is not attached to this local workspace.</p>}</>}</div></Modal>
}
function EventCard({event,onReceipt,selected=false}:{event:PatientEvent;onReceipt:(r:Receipt)=>void;selected?:boolean}){
 const w=useWorkspace();const [approved,setApproved]=useState(event.body.owner_approved===true);
 const missing=event.flags.some(f=>f.type==='missing_source');
 return <article id={'event-'+event.id} className={'spine-event '+(selected?'focused-event':'')}><div className="event-top"><Badge>{event.event_type.replaceAll('_',' ')}</Badge><time>{new Date(event.occurred_at).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit'})}</time></div><h3>{event.summary}</h3><p className="muted">{event.actor.name}</p>{missing&&<span className="needs-checking">◌ Source needed · needs checking</span>}{event.observations.map(o=><div className="inline-measurement" key={o.id}><span>{o.name}</span><strong>{typeof o.value==='boolean'?(o.value?'Yes':'No'):o.value} {o.unit}</strong><span className="muted">{o.ref_low!=null||o.ref_high!=null?`Reference ${o.ref_low??'—'}–${o.ref_high??'—'} ${o.unit}`:'No reference range supplied'}</span>{o.flag&&<Badge tone="amber">{o.flag==='high'?'↑ High':'↓ Low'}</Badge>}{o.source&&<button className="text-button" onClick={()=>onReceipt(o.source!)}>Source ↗</button>}</div>)}{typeof event.body.text==='string'&&<details><summary>Recorded text</summary><p className="preserve">{event.body.text}</p></details>}{event.source&&<button className="text-button" onClick={()=>onReceipt(event.source!)}>↗ {event.source.kind==='document'?'Document':event.source.kind==='audio'?'Audio note':'Source'}{event.source.page?' · page '+event.source.page:''}{event.source.start_ms!=null?' · '+(event.source.start_ms/1000).toFixed(1)+'s':''}</button>}{!event.body.legacy&&w.snapshot?.permissions.includes('clinical.approve')&&<button className="text-button" onClick={()=>{void w.act('clinical.approve',{id:event.id,approved:!approved}).then(()=>setApproved(!approved)).catch(()=>{})}}>{approved?'Remove from owner vault':'Approve for owner vault'}</button>}</article>
}
export function PatientTimeline({patientId}:{patientId:string}){
 const w=useWorkspace();const revision=w.records.filter(r=>r.data.patient_id===patientId).map(r=>r.id+':'+r.version).join(',');
 const [category,setCategory]=useState(''),[q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null);
 const page=usePage<PatientEvent>('/v2/patients/'+encodeURIComponent(patientId)+'/timeline?limit=20&category='+encodeURIComponent(category)+'&q='+encodeURIComponent(q)+(from?'&start='+from:'')+(to?'&end='+to:''),revision);
 const groups:Record<string,PatientEvent[]>={};page.items.forEach(e=>{const date=new Date(e.occurred_at).toLocaleDateString('en-SG',{day:'numeric',month:'long',year:'numeric'});(groups[date]??=[]).push(e)});
 return <><div className="record-filters"><input aria-label="Search timeline" placeholder="Search the timeline" value={q} onChange={e=>setQ(e.target.value)}/><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="text-button" onClick={page.refresh}>Refresh</button></div><div className="filter-chips">{[['','All'],['lab_result','Bloods'],['cytology','Cytology'],['x_ray','X-ray'],['consult','Consults'],['vaccination','Vaccines'],['invoice','Invoices'],['message','Messages']].map(([value,label])=><button key={value} className={category===value?'selected':''} onClick={()=>setCategory(value)}>{label}</button>)}</div><div className="spine-timeline relative">{Object.entries(groups).map(([day,events])=><section key={day}><h2 className="timeline-day">{day}</h2>{events.map(e=><EventCard key={e.id} event={e} onReceipt={setReceipt}/>)}</section>)}{page.loading&&<p role="status" className="spine-state">Loading timeline…</p>}{page.error&&<Failure message={page.error} retry={page.retry}/>} {!page.loading&&!page.error&&!page.items.length&&<Empty title="No events in this view" text="Results can arrive here without an appointment or consultation."/>}<div ref={page.sentinel}/>{page.cursor&&!page.loading&&<button className="text-button spine-more" onClick={page.more}>Load earlier events</button>}</div>{receipt&&<ReceiptView receipt={receipt} onClose={()=>setReceipt(null)}/>}</>
}
export function PatientAnalytics({patientId}:{patientId:string}){
 const clinic=useWorkspace().snapshot?.clinic.id;
 const [terms,setTerms]=useState<any[]>([]),[term,setTerm]=useState(''),[data,setData]=useState<Series|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0),[event,setEvent]=useState<PatientEvent|null>(null),[receipt,setReceipt]=useState<Receipt|null>(null);
 useEffect(()=>{let live=true;setLoading(true);setError('');setTerms([]);setTerm('');setData(null);void api('/v2/patients/'+encodeURIComponent(patientId)+'/concepts').then(r=>{if(live){r=r.filter((t:any)=>t.value_type==='number');setTerms(r);setTerm((r.find((t:any)=>t.code==='potassium')||r[0])?.id||'');if(!r.length)setLoading(false)}}).catch(e=>{if(live){setError(e.message);setLoading(false)}});return()=>{live=false}},[patientId,clinic,attempt]);
 useEffect(()=>{if(!term)return;let live=true;setLoading(true);setData(null);setError('');void api('/v2/patients/'+encodeURIComponent(patientId)+'/observations?concept='+encodeURIComponent(term)).then(r=>{if(live)setData(r)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[term,patientId,clinic,attempt]);
 const open=async(id:string)=>{try{setEvent(await api('/v2/patients/'+encodeURIComponent(patientId)+'/events/'+encodeURIComponent(id)))}catch(e){setError((e as Error).message)}};
 return <div className="spine-analytics min-w-0"><div className="section-heading"><div><h3>Measurements over time</h3><p>Recorded values with the reporting laboratory’s reference range.</p></div>{terms.length>0&&<select aria-label="Clinical marker" value={term} onChange={e=>setTerm(e.target.value)}>{terms.map(t=><option key={t.id} value={t.id}>{t.name} · {t.unit}</option>)}</select>}</div>{loading&&<p role="status" className="spine-state">Loading measurements…</p>}{error&&<Failure message={error} retry={()=>setAttempt(n=>n+1)}/>} {!loading&&!error&&(!data||!data.series.length)&&<Empty title="No measurements yet" text="A lab result will appear without needing a consultation."/>}{data&&data.series.length>0&&<ReferenceChart data={data} onPoint={open}/>} {event&&<Modal title="Source event" onClose={()=>setEvent(null)}><div className="modal-body"><p className="mono-label">{new Date(event.occurred_at).toLocaleString('en-SG')}</p><EventCard event={event} onReceipt={setReceipt} selected/></div></Modal>}{receipt&&<ReceiptView receipt={receipt} onClose={()=>setReceipt(null)}/>}</div>
}
function ReferenceChart({data,onPoint}:{data:Series;onPoint:(id:string)=>void}){
 const rows=data.series,values=rows.flatMap(r=>[r.value,...(r.ref_low==null?[]:[r.ref_low]),...(r.ref_high==null?[]:[r.ref_high])]);const min=Math.min(...values),max=Math.max(...values),pad=(max-min||1)*.15,lo=min-pad,hi=max+pad;
 const times=rows.map(r=>Date.parse(r.observed_at)),first=Math.min(...times),last=Math.max(...times),x=(t:number)=>first===last?350:65+(t-first)/(last-first)*570,y=(v:number)=>240-(v-lo)/(hi-lo)*195;
 return <><svg className="reference-chart" viewBox="0 0 700 300" role="img" aria-label={data.concept.name+' over time with shaded laboratory reference range'}>{[0,1,2,3,4].map(i=>{const v=lo+(hi-lo)*i/4;return <g key={i}><line x1="65" x2="635" y1={y(v)} y2={y(v)} stroke="#e7e5e4"/><text x="55" y={y(v)+4} textAnchor="end" fontSize="11" fill="currentColor">{v.toFixed(1)}</text></g>})}{rows.map((r,i)=>{if(r.ref_low==null||r.ref_high==null)return null;const left=i===0?65:(x(times[i-1])+x(times[i]))/2,right=i===rows.length-1?635:(x(times[i])+x(times[i+1]))/2;return <rect key={'band'+i} x={left} y={y(r.ref_high)} width={Math.max(1,right-left)} height={Math.max(1,y(r.ref_low)-y(r.ref_high))} fill="#d8d8d0" opacity=".45"><title>Laboratory reference: {r.ref_low}–{r.ref_high} {data.concept.unit}</title></rect>})}<polyline points={rows.map((r,i)=>x(times[i])+','+y(r.value)).join(' ')} fill="none" stroke="#44403c" strokeWidth="2"/>{rows.map((r,i)=><g key={r.event_id+':'+i} role="button" tabIndex={0} aria-label={`${data.concept.name} ${r.value} ${data.concept.unit}, ${new Date(r.observed_at).toLocaleDateString('en-SG')}, ${r.flag||'not flagged'}. Open source event`} onClick={()=>onPoint(r.event_id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onPoint(r.event_id)}}}><circle cx={x(times[i])} cy={y(r.value)} r="7" fill={r.flag?'#916025':'#0d9488'} stroke="white" strokeWidth="2"/><title>{r.value} {data.concept.unit} · Reference {r.ref_low??'—'}–{r.ref_high??'—'}</title></g>)}<text x="65" y="274" fontSize="11" fill="currentColor">{new Date(first).toLocaleDateString('en-SG')}</text><text x="635" y="274" fontSize="11" textAnchor="end" fill="currentColor">{new Date(last).toLocaleDateString('en-SG')}</text><text x="65" y="22" fontSize="11" fill="currentColor">{data.concept.unit}</text></svg><p className="chart-caption">Shaded band: range supplied with each result. Click a point to open its event. No supplied range means no band or range flag.</p><div className="table-wrap"><table><thead><tr><th>Observed</th><th>Value</th><th>Reference</th><th>Flag</th><th>Event</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.event_id+':'+i}><td>{new Date(r.observed_at).toLocaleDateString('en-SG')}</td><td>{r.value} {data.concept.unit}</td><td>{r.ref_low??'—'}–{r.ref_high??'—'}</td><td>{r.flag||'—'}</td><td><button className="text-button" onClick={()=>onPoint(r.event_id)}>Open event ↗</button></td></tr>)}</tbody></table></div></>
}

export function PatientRecordStats({patientId}:{patientId:string}){const clinic=useWorkspace().snapshot?.clinic.id;const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{let live=true;setData(null);setError('');void api('/v2/patients/'+encodeURIComponent(patientId)).then(r=>{if(live)setData(r.stats)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[patientId,clinic]);return <section className="panel"><h2>On the record</h2>{error?<p className="muted">Counts unavailable</p>:data?[['Recorded visits',data.visits],['Measurements',data.observations],['Document sources',data.document_sources]].map(([label,n])=><div key={label} className="aside-stat"><span>{label}</span><strong>{n}</strong></div>):<p role="status" className="muted">Loading counts…</p>}</section>}

export function StandalonePatientRecord({patientId}:{patientId:string}){
 const clinic=useWorkspace().snapshot?.clinic.id;const [patient,setPatient]=useState<PatientV2|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[tab,setTab]=useState('Timeline');
 useEffect(()=>{let live=true;setPatient(null);setError('');void api('/v2/patients/'+encodeURIComponent(patientId)).then(p=>{if(live)setPatient(p)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[patientId,clinic,attempt]);
 if(error)return <Failure message={error} retry={()=>setAttempt(n=>n+1)}/>;if(!patient)return <p role="status" className="spine-state">Loading patient…</p>;
 const dob=patient.date_of_birth?new Date(patient.date_of_birth+'T00:00:00Z'):null,now=new Date();let age=dob?now.getUTCFullYear()-dob.getUTCFullYear():null;if(dob&&age!==null&&(now.getUTCMonth()<dob.getUTCMonth()||(now.getUTCMonth()===dob.getUTCMonth()&&now.getUTCDate()<dob.getUTCDate())))age--;
 return <><button className="back-link" onClick={()=>navigate('Patients')}>← All patients</button><div className="patient-header"><div><h1>{patient.name}</h1><p>{patient.species} · {patient.breed} · {age!==null?age+' years':'Age not recorded'}</p></div></div><div className="patient-facts"><div><span>OWNER</span><strong>{patient.owner?.name||'Not linked'}</strong></div><div><span>DATE OF BIRTH</span><strong>{patient.date_of_birth||'Not recorded'}</strong></div><div><span>PATIENT ID</span><strong>{patient.id}</strong></div></div><div className="record-layout"><section className="panel"><div className="panel-heading"><div className="tabs">{['Timeline','Observations'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div></div>{tab==='Timeline'?<PatientTimeline patientId={patientId}/>:<PatientAnalytics patientId={patientId}/>}</section><aside className="patient-aside"><PatientRecordStats patientId={patientId}/></aside></div></>
}
