'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {useWorkspace} from '@/lib/workspace';
import {Badge,BusyButton,Form,Modal} from './ui';

type Item={reminder_id:string;title:string;due:string;patient_name:string;owner_id:string|null;contact:{name?:string;phone?:string;email?:string};blocked_reason:string;outbox_id?:string;status?:string};
type Review={start:string;end:string;query:string;digest:string;items:Item[]};

export function RecallCampaigns(){
 const w=useWorkspace();
 return <CampaignWorkspace key={w.snapshot?.clinic.id+':'+w.snapshot?.actor.id}/>;
}
function CampaignWorkspace(){
 const w=useWorkspace(),permissions=w.snapshot?.permissions||[];
 const [review,setReview]=useState<Review|null>(null),[name,setName]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const [campaignId,setCampaignId]=useState(''),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[ownerId,setOwnerId]=useState('');
 const campaigns=w.records.filter(r=>r.kind==='recall_campaign'),owner=w.records.find(r=>r.id===ownerId&&r.kind==='owner');
 useEffect(()=>{let active=true;setError('');if(!campaignId){setDetail(null);return}void api('/recalls/'+campaignId).then(r=>{if(active)setDetail(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[campaignId,w.snapshot]);
 return <section className="panel section-gap" aria-label="Recall campaigns"><div className="panel-heading"><div><h2>Recall campaigns</h2><p>Review up to 100 reminders at a time, then prepare selected drafts.</p></div><Badge tone="amber">Manual delivery</Badge></div>
 <div className="modal-body"><p>Preparation does not send messages. Each reminder keeps its delivery history; cancelled or previously prepared reminders are never retried automatically.</p>
 {campaigns.map(r=><button className="visit-row" key={r.id} onClick={()=>{setDetail(null);setCampaignId(r.id)}}><strong>{r.data.title}</strong><span>{r.data.review.start} – {r.data.review.end}</span><Badge>{r.data.status}</Badge></button>)}{!campaigns.length&&<p>No campaigns prepared yet.</p>}</div>
 {permissions.includes('recall.prepare')&&<Form submit="Preview reminders" fields={[{name:'start',label:'Due from',type:'date',required:true},{name:'end',label:'Due through',type:'date',required:true},{name:'query',label:'Reminder title contains (optional)'}]} onSubmit={async p=>{const r=await api('/recalls/preview',{method:'POST',body:JSON.stringify(p)});setReview(r);setSelected(r.items.filter((x:Item)=>!x.blocked_reason).map((x:Item)=>x.reminder_id));setName('')}}/>}
 {permissions.includes('owner.recall_preference')&&<details className="modal-body"><summary>Owner recall preferences</summary><p>Record an owner’s explicit request. Opting out cancels their pending reminder drafts, including drafts outside campaigns. It does not change other care messages.</p><label>Owner<select aria-label="Recall preference owner" value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Choose owner</option>{w.records.filter(r=>r.kind==='owner'&&!r.data.merged_into).map(r=><option key={r.id} value={r.id}>{r.data.name} · {r.data.phone||r.data.email||'No contact recorded'}</option>)}</select></label>
 {owner&&<><p>Current preference: {owner.data.recall_opt_out?'Opted out':'Not opted out (not evidence of messaging consent)'}</p><Form key={owner.id+':'+owner.version} submit="Save recall preference" fields={[{name:'opt_out',label:'Recall preference',value:String(!!owner.data.recall_opt_out),options:[{value:'true',label:'Owner opted out'},{value:'false',label:'Owner withdrew their opt-out'}]},{name:'reason',label:'Reason / owner request',required:true,type:'textarea'}]} onSubmit={async p=>{await w.act('owner.recall_preference',{id:owner.id,version:owner.version,opt_out:p.opt_out==='true',reason:p.reason});setReview(null);w.notify('Recall preference saved')}}/>{owner.data.recall_preferences?.map((r:any,i:number)=><p key={i}>{r.opt_out?'Opted out':'Opt-out withdrawn'} · {new Date(r.at).toLocaleString()} · {r.reason}</p>)}</>}</details>}
 {review&&<Modal title="Review recall campaign" onClose={()=>setReview(null)} wide><div className="modal-body"><p>{review.start} – {review.end} · {selected.length} selected of {review.items.length}. Confirm patient, primary owner and contact details before preparing.</p><label>Campaign name<input value={name} onChange={e=>setName(e.target.value)} maxLength={160}/></label>{review.items.map(item=><article className="history-entry" key={item.reminder_id}><label><input type="checkbox" disabled={!!item.blocked_reason} checked={selected.includes(item.reminder_id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,item.reminder_id]:ids.filter(id=>id!==item.reminder_id))}/><strong>{item.patient_name} · {item.title}</strong></label><p>Due {item.due} · {item.contact.name} · {item.contact.phone||item.contact.email||'No phone or email recorded; confirm another contact method'}</p>{item.blocked_reason?<p>{item.blocked_reason}</p>:<p className="preserve">Reminder for {item.patient_name}: {item.title}, due {item.due}. Please contact your clinic to arrange this.</p>}</article>)}{!review.items.length&&<p>No reminders match this period and search.</p>}<BusyButton className="primary" disabled={!selected.length||name.trim().length<3} onClick={async()=>{const r=await w.act('recall.prepare',{start:review.start,end:review.end,query:review.query,digest:review.digest,title:name,reminder_ids:selected});setReview(null);setDetail(null);setCampaignId(r.id);w.notify('Selected drafts prepared. Nothing was sent.')}}>Prepare {selected.length} selected drafts</BusyButton></div></Modal>}
 {campaignId&&<Modal title="Recall campaign progress" onClose={()=>setCampaignId('')} wide><div className="modal-body">{error&&<p role="alert" className="error">{error}</p>}{!detail&&!error&&<p>Loading campaign…</p>}{detail&&<><h3>{detail.data.title}</h3><p>{detail.data.status} · Reviewed by {w.records.find(r=>r.id===detail.data.prepared_by)?.data.name||detail.data.prepared_by} · {new Date(detail.data.prepared_at).toLocaleString()}</p><p>{Object.entries(detail.counts).map(([state,count])=>`${state.replaceAll('_',' ')}: ${count}`).join(' · ')}</p><p>“Sent manually” is a staff record, not a provider delivery receipt. Prepared messages are in the Outbox.</p>{detail.items.map((item:Item)=><article className="history-entry" key={item.reminder_id}><strong>{item.patient_name} · {item.title}</strong><p>{item.contact.name} · Due {item.due} · {item.status?.replaceAll('_',' ')}</p>{item.blocked_reason&&<p>{item.blocked_reason}</p>}</article>)}{detail.data.cancel_reason&&<p>Cancelled: {detail.data.cancel_reason}</p>}</>}</div>{detail?.data.status==='prepared'&&permissions.includes('recall.cancel')&&<Form key={detail.version} submit="Cancel remaining drafts" fields={[{name:'reason',label:'Cancellation reason',required:true,type:'textarea'}]} onSubmit={async p=>{await w.act('recall.cancel',{id:detail.id,version:detail.version,reason:p.reason});w.notify('Pending campaign drafts cancelled. Delivery history preserved.')}}/>}</Modal>}
 </section>;
}
