'use client';
export type TrendPoint={record_id?:string;version?:number;event_id?:string;observed_at:string;time_basis?:'observed'|'recorded';value:number;ref_low:number|null;ref_high:number|null;flag:string|null};
export type TrendSeries={concept:{name:string;code?:string;unit:string};series:TrendPoint[];timezone?:string};
export function ReferenceChart({data,onPoint,sourceLabel='event'}:{data:TrendSeries;onPoint:(id:string)=>void;sourceLabel?:'event'|'record'}){
 const dateLabel=(value:string|number)=>new Date(value).toLocaleDateString('en-SG',{timeZone:data.timezone});
 const identity=(point:TrendPoint)=>point.record_id||point.event_id||'';
 if(!data.series.length)return <p>No matching numeric observations are recorded for these filters.</p>;
 const rows=data.series,values=rows.flatMap(r=>[r.value,...(r.ref_low==null?[]:[r.ref_low]),...(r.ref_high==null?[]:[r.ref_high])]);const min=Math.min(...values),max=Math.max(...values),pad=(max-min||1)*.15,lo=min-pad,hi=max+pad;
 const times=rows.map(r=>Date.parse(r.observed_at)),first=Math.min(...times),last=Math.max(...times),x=(t:number)=>first===last?350:65+(t-first)/(last-first)*570,y=(v:number)=>240-(v-lo)/(hi-lo)*195;
 return <><p>{data.concept.name}{data.concept.code?' · code: '+data.concept.code:''} · {data.concept.unit}{data.timezone?' · '+data.timezone:''}</p><svg className="reference-chart" viewBox="0 0 700 300" role="img" aria-label={data.concept.name+' over time with supplied reference ranges'}>{[0,1,2,3,4].map(i=>{const v=lo+(hi-lo)*i/4;return <g key={i}><line x1="65" x2="635" y1={y(v)} y2={y(v)} stroke="#e7e5e4"/><text x="55" y={y(v)+4} textAnchor="end" fontSize="11" fill="currentColor">{v.toFixed(1)}</text></g>})}{rows.map((r,i)=>{if(r.ref_low==null||r.ref_high==null)return null;const left=i===0?65:(x(times[i-1])+x(times[i]))/2,right=i===rows.length-1?635:(x(times[i])+x(times[i+1]))/2;return <rect key={'band'+i} x={left} y={y(r.ref_high)} width={Math.max(1,right-left)} height={Math.max(1,y(r.ref_low)-y(r.ref_high))} fill="#d8d8d0" opacity=".45"><title>Supplied reference: {r.ref_low}–{r.ref_high} {data.concept.unit}</title></rect>})}<polyline points={rows.map((r,i)=>x(times[i])+','+y(r.value)).join(' ')} fill="none" stroke="#44403c" strokeWidth="2"/>{rows.map((r,i)=><g key={identity(r)+':'+i} role="button" tabIndex={0} aria-label={`${data.concept.name} ${r.value} ${data.concept.unit}, ${dateLabel(r.observed_at)}, ${r.flag||'not flagged'}. Open source ${sourceLabel}`} onClick={()=>onPoint(identity(r))} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onPoint(identity(r))}}}><circle cx={x(times[i])} cy={y(r.value)} r="7" fill={r.flag?'#916025':'#0d9488'} stroke="white" strokeWidth="2"/><title>{r.value} {data.concept.unit} · Reference {r.ref_low??'—'}–{r.ref_high??'—'}</title></g>)}<text x="65" y="274" fontSize="11" fill="currentColor">{dateLabel(first)}</text><text x="635" y="274" fontSize="11" textAnchor="end" fill="currentColor">{dateLabel(last)}</text><text x="65" y="22" fontSize="11" fill="currentColor">{data.concept.unit}</text></svg><p className="chart-caption">Shaded band: both bounds supplied with that result. Missing bounds are shown as —; no range is inferred. Lines join recorded points only; gaps do not imply zero or continuous monitoring. Click a point to open its {sourceLabel}.</p><div className="table-wrap"><table><thead><tr><th>Date</th><th>Time basis</th><th>Value</th><th>Reference</th><th>Flag</th><th>Source</th></tr></thead><tbody>{rows.map((r,i)=><tr key={identity(r)+':'+i}><td>{dateLabel(r.observed_at)}</td><td>{r.time_basis==='recorded'?'Record timestamp':'Observed'}</td><td>{r.value} {data.concept.unit}</td><td>{r.ref_low??'—'}–{r.ref_high??'—'}</td><td>{r.flag||'—'}</td><td><button className="text-button" onClick={()=>onPoint(identity(r))}>Open {sourceLabel}{r.version!=null?' v'+r.version:''} ↗</button></td></tr>)}</tbody></table></div></>
}
