'use client';
import {SpeakerLabels} from './WorkflowControls';
import React,{useEffect,useRef,useState} from 'react';
import {X,SpinnerGap,ArrowUpRight,FileText,Check,WarningCircle} from '@phosphor-icons/react';
import {Row,speciesClass} from '@/lib/types';
import {useWorkspace} from '@/lib/workspace';
import {api,headers} from '@/lib/api';
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Empty({title,text,action}:{title:string;text?:string;action?:React.ReactNode}){return <div className="empty"><FileText size={28}/><h3>{title}</h3>{text&&<p>{text}</p>}{action}</div>}
export function PatientMark({patient,large=false}:{patient:Row;large?:boolean}){return <span className={'patient-mark '+speciesClass(patient.data.species)+(large?' large':'')}>{patient.data.name.slice(0,1)}</span>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>{ref.current?.close()}},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><header><h2>{title}</h2><button className="icon" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header>{children}</dialog>}
export type Field={name:string;label:string;type?:string;value?:any;required?:boolean;options?:{value:string;label:string}[];placeholder?:string;min?:number;step?:string;wide?:boolean};
export function Form({fields,onSubmit,submit='Save',children}:{fields:Field[];onSubmit:(data:any)=>Promise<any>;submit?:string;children?:React.ReactNode}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="form" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const values=Object.fromEntries(new FormData(e.currentTarget).entries());try{await onSubmit(values)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="form-grid">{fields.map(f=><label className={f.wide?'span2':''} key={f.name}><span>{f.label}</span>{f.options?<select name={f.name} defaultValue={f.value||''} required={f.required}>{!f.value&&<option value="">Select…</option>}{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} rows={4} defaultValue={f.value||''} placeholder={f.placeholder} required={f.required}/>:<input name={f.name} type={f.type||'text'} defaultValue={f.value??''} placeholder={f.placeholder} required={f.required} min={f.min} step={f.step}/>}</label>)}</div>{children}{error&&<p role="alert" className="error"><WarningCircle size={17}/>{error}</p>}<footer><button className="primary" disabled={busy}>{busy?<SpinnerGap className="spin" size={17}/>:<Check size={17}/>} {busy?'Saving…':submit}</button></footer></form>}
export function SourceModal({source:initialSource,onClose}:{source:Row;onClose:()=>void}){
 const {records}=useWorkspace();const source=records.find(r=>r.id===initialSource.id)||initialSource;const ids=source.data.source_ids||(source.data.source_id?[source.data.source_id]:[]);const [url,setUrl]=useState(''),[error,setError]=useState('');const audio=useRef<HTMLAudioElement>(null);const [seek,setSeek]=useState(0);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 const play=async(time:number)=>{setSeek(time);if(url&&audio.current){audio.current.currentTime=time;await audio.current.play();return}try{const r=await fetch('/api/recordings/'+source.data.recording_id+'/audio',{headers:headers()});if(!r.ok)throw new Error('Original audio is unavailable');setUrl(URL.createObjectURL(await r.blob()))}catch(e){setError((e as Error).message)}};
 return <Modal title="Source receipt" onClose={onClose}><div className="modal-body"><Badge tone={source.data.machine_transcript?'amber':'teal'}>{source.data.machine_transcript?'Machine transcript · listen to verify':'Original record'}</Badge><h3>{source.data.title||source.data.name||source.kind}</h3><p className="preserve">{source.data.text||source.data.body||JSON.stringify(source.data,null,2)}</p>{url&&<audio ref={audio} src={url} controls autoPlay onLoadedMetadata={()=>{if(audio.current)audio.current.currentTime=seek}}/>}{error&&<p className="error">{error}</p>}{source.data.utterances?.length>0&&<div className="transcript-segments"><h3>Audio timestamps</h3>{source.data.refinement_windows?.length>1&&<p className="integration-note">{source.data.refinement_windows.length} speech windows. Speaker numbers restart in each window; matching numbers do not identify the same person across windows.</p>}{source.data.utterances.map((u:any,i:number)=><button key={i} onClick={()=>void play(u.start)}><time>{Math.floor(u.start/60)}:{String(Math.floor(u.start%60)).padStart(2,'0')}</time><b>{source.data.speaker_labels?.[String(u.speaker)]||(u.speaker==null?'Audio':'Speaker '+u.speaker)}: </b>{u.text}</button>)}</div>}<SpeakerLabels source={source}/><div className="meta-box"><span>Recorded</span><b>{new Date(source.created_at).toLocaleString('en-SG')}</b><span>Record ID</span><code>{source.id}</code>{source.data.author&&<><span>Author</span><b>{source.data.author}</b></>}</div>{ids.map((id:string)=>{const s=records.find(r=>r.id===id);return s?<article className="source-quote" key={id}><strong>{s.data.title}</strong><p className="preserve">{s.data.text}</p><small>{s.id}</small></article>:null})}</div></Modal>
}
export function HistoryModal({id,onClose}:{id:string;onClose:()=>void}){const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{void api('/records/'+id+'/history').then(setData).catch(e=>setError(e.message))},[id]);return <Modal title="Record revision history" onClose={onClose} wide><div className="modal-body">{error&&<p className="error">{error}</p>}{!data&&!error&&<p>Loading revisions…</p>}{data&&<><p>Current revision {data.current.version}. Earlier versions remain unchanged.</p>{data.versions.map((v:any)=><details className="history-entry" key={v.version}><summary>Revision {v.version} · {new Date(v.recorded_at).toLocaleString('en-SG')}</summary><pre>{JSON.stringify(v.data,null,2)}</pre><button className="secondary" onClick={()=>void navigator.clipboard.writeText(JSON.stringify(v.data,null,2))}>Copy this revision</button></details>)}{!data.versions.length&&<p>No earlier revisions.</p>}</>}</div></Modal>}
export const patientOptions=(records:Row[])=>records.filter(r=>r.kind==='patient').map(r=>({value:r.id,label:`${r.data.name} · ${r.data.species} · ${records.find(o=>o.id===r.data.owner_id)?.data.name||''}`}));
export function BusyButton({children,onClick,className='secondary',disabled=false}:{children:React.ReactNode;onClick:()=>Promise<any>;className?:string;disabled?:boolean}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <><button className={className} disabled={busy||disabled} onClick={async()=>{setError('');setBusy(true);try{await onClick()}catch(e){setError(e instanceof Error?e.message:'The action could not finish. Please try again.')}finally{setBusy(false)}}}>{busy?<SpinnerGap size={16} className="spin"/>:null}{children}</button>{error&&<span className="error" role="alert">{error}</span>}</>}

export function download(name:string,content:string,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
