'use client';
import React,{useEffect,useRef,useState} from 'react';
import {CheckCircle,CalendarBlank,Pill,FileText,ShieldCheck,Microphone,LinkSimple} from '@phosphor-icons/react';
import {PatientMark,Badge} from '@/components/ui';
export default function Owner(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[token,setToken]=useState(''),[tab,setTab]=useState('Records'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[share,setShare]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<any>(null);
 const submission=useRef({body:'',key:''});
 useEffect(()=>{const t=new URLSearchParams(location.search).get('token')||'';setToken(t);fetch(t?'/api/owner/'+encodeURIComponent(t):'/api/owner-account').then(async r=>{const b=await r.json();if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:'Open a valid clinic link to continue.');setData(b)}).catch(e=>setError(e.message))},[]);
 const base=token?'/api/owner/'+encodeURIComponent(token):'/api/owner-account';
 const post=async(path:string,body:any={})=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:'This request could not be saved');return b};
 return <main className="owner-page"><span className="wordmark">Broby<span>•</span></span>{!data?<p>{error||'Opening your pet’s approved record…'}</p>:<><div className="owner-header"><PatientMark patient={data.patient} large/><div><Badge tone="teal"><ShieldCheck size={13}/> Shared by your clinic</Badge><h1>{data.patient.data.name}’s record</h1><p className="muted">{data.patient.data.breed} · {data.patient.data.age}</p></div></div><p className="muted section-gap">Your veterinarian’s approved notes, prescribed medications, and upcoming care.</p>
 {token&&<div className="actions section-gap"><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await post('/claim');setNotice('Access saved on this browser. You can return to /owner without signing up.')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}>Save access on this device</button><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await post('/share');setShare(location.origin+r.url)}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}><LinkSimple size={15}/> Create referral link</button></div>}
 {share&&<div className="inline-notice"><label>Read-only approved records · share this link with the receiving clinic<input readOnly value={share}/></label><button className="secondary" onClick={()=>void navigator.clipboard.writeText(share)}>Copy</button></div>}{notice&&<p role="status" className="inline-notice">{notice}</p>}
 <div className="tabs owner-tabs">{['Records','Before your visit','Ask the clinic'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Records'&&<><section className="panel"><div className="panel-heading"><h2>Visit history</h2><FileText size={18}/></div><div className="event-list">{data.events.map((e:any)=><article className="event" key={e.id}><div className="event-icon"><CheckCircle size={18}/></div><div className="event-content"><div className="event-top"><Badge tone="teal">Approved</Badge><time>{new Date(e.data.occurred_at).toLocaleDateString('en-SG')}</time></div><h3>{e.data.title}</h3><p className="preserve">{e.data.body}</p></div></article>)}{!data.events.length&&<p className="muted">No visit records have been shared yet.</p>}</div></section><section className="panel"><div className="panel-heading"><h2>Medications</h2><Pill size={19}/></div>{data.medications.length?data.medications.map((m:any)=><div className="owner-med" key={m.id}><strong>{m.data.name}</strong><p>{m.data.dose} · {m.data.frequency}</p><p>{m.data.instructions}</p></div>):<div className="owner-med"><p>No medications have been recorded.</p></div>}</section><section className="panel"><div className="panel-heading"><h2>What’s due</h2><CalendarBlank size={19}/></div>{data.reminders.filter((r:any)=>r.data.status==='due').map((r:any)=><div className="owner-med" key={r.id}><strong>{r.data.title}</strong><p>{r.data.due}</p></div>)}</section><section className="panel"><div className="panel-heading"><h2>Shared documents</h2><FileText size={19}/></div>{data.files?.length?data.files.map((f:any)=><div className="owner-med" key={f.id}><a href={base+'/files/'+f.id}>{f.data.name}</a></div>):<div className="owner-med">No documents shared yet.</div>}</section><section className="panel"><div className="panel-heading"><h2>Your vet’s explanation</h2><Microphone size={19}/></div>{data.audio?.length?data.audio.map((r:any)=><div className="owner-med" key={r.id}><strong>Voice note {r.data.number}</strong><audio controls preload="none" src={base+'/audio/'+r.id}/></div>):<div className="owner-med">No audio explanations shared yet.</div>}</section></>}
 {tab==='Before your visit'&&<section className="panel"><div className="panel-heading"><h2>Tell the clinic what’s changed</h2></div>{<form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setNotice('');const form=e.currentTarget;const fields=Object.fromEntries(new FormData(form).entries());const body={...fields,urgent:fields.urgent==='on'};const serialized=JSON.stringify(body);if(submission.current.body!==serialized)submission.current={body:serialized,key:crypto.randomUUID()};try{await post('/intake',{...body,key:submission.current.key});setNotice('Your information was received and is waiting for the clinic to review.');form.reset();submission.current={body:'',key:''}}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}><label>Reason for the visit<textarea name="reason" required maxLength={4000} rows={4}/></label><label>Appetite and drinking<textarea name="appetite" maxLength={1000}/></label><label>Current medications<textarea name="medications" maxLength={2000}/></label><label>Questions for your veterinarian<textarea name="questions" maxLength={2000}/></label><label className="feature-lock"><input type="checkbox" name="urgent"/> I want the clinic to know this is urgent</label><p className="integration-note">This form is not monitored continuously. For urgent concerns, call {data.emergency_phone||'your clinic or an emergency veterinary service'} directly.</p><button className="primary" disabled={busy}>{busy?'Submitting…':'Submit to clinic'}</button></form>}</section>}
 {tab==='Ask the clinic'&&<section className="panel"><div className="panel-heading"><h2>Saved care instructions</h2></div><div className="form"><p>Retrieve medication instructions and reminders already recorded by your clinic.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{setAnswer(await post('/help',{message:question}))}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}}><label>Your question<input value={question} onChange={e=>setQuestion(e.target.value)} required placeholder="What medication instructions were shared?"/></label><button className="primary" disabled={busy}>Show saved information</button></form>{answer&&<><p className="preserve">{answer.text}</p><p className="integration-note">{answer.notice}</p>{answer.emergency_phone&&<a href={'tel:'+answer.emergency_phone}>Call clinic: {answer.emergency_phone}</a>}</>}</div></section>}
 <p className="owner-footnote">{data.saved_access?'Saved access':'This private link'} expires {new Date(data.expires_at).toLocaleDateString('en-SG')}. Access may be revoked by the clinic. Contact your clinic for medical questions.</p></>}</main>
}
